"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from deprecation import deprecated

from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.apis.base_api import (
    BaseApi,
)
from openapispecforclickhousecloud.configuration import (
    Server,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_service_profiles_400_error_exception import (  # noqa: E501
    V1OrganizationsServiceProfiles400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_service_profiles_500_error_exception import (  # noqa: E501
    V1OrganizationsServiceProfiles500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_400_error_exception import (  # noqa: E501
    V1OrganizationsServices400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_500_error_exception import (  # noqa: E501
    V1OrganizationsServices500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_clickhouse_settings_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettings400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_clickhouse_settings_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettings500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_clickhouse_settings_schema_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSchema400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_clickhouse_settings_schema_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSchema500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_clickhouse_settings_setting_name_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSettingName400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_clickhouse_settings_setting_name_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSettingName500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_password_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesPassword400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_password_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesPassword500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_private_endpoint_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesPrivateEndpoint400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_private_endpoint_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesPrivateEndpoint500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_private_endpoint_config_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesPrivateEndpointConfig400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_private_endpoint_config_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesPrivateEndpointConfig500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_replica_scaling_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesReplicaScaling400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_replica_scaling_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesReplicaScaling500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_scaling_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesScaling400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_scaling_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesScaling500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_scaling_schedule_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesScalingSchedule400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_scaling_schedule_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesScalingSchedule500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_service_query_endpoint_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesServiceQueryEndpoint400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_service_query_endpoint_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesServiceQueryEndpoint500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_state_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesState400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_state_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesState500ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_upgrade_window_400_error_exception import (  # noqa: E501
    V1OrganizationsServicesUpgradeWindow400ErrorException,
)
from openapispecforclickhousecloud.exceptions.v_1_organizations_services_upgrade_window_500_error_exception import (  # noqa: E501
    V1OrganizationsServicesUpgradeWindow500ErrorException,
)
from openapispecforclickhousecloud.http.http_method_enum import (
    HttpMethodEnum,
)
from openapispecforclickhousecloud.models.v_1_organizations_service_profiles_response import (  # noqa: E501
    V1OrganizationsServiceProfilesResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_clickhouse_settings_response import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_clickhouse_settings_response_1 import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsResponse1,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_clickhouse_settings_schema_response import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSchemaResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_clickhouse_settings_setting_name_response import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSettingNameResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_clickhouse_settings_setting_name_response_1 import (  # noqa: E501
    V1OrganizationsServicesClickhouseSettingsSettingNameResponse1,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_password_response import (  # noqa: E501
    V1OrganizationsServicesPasswordResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_private_endpoint_config_response import (  # noqa: E501
    V1OrganizationsServicesPrivateEndpointConfigResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_private_endpoint_response import (  # noqa: E501
    V1OrganizationsServicesPrivateEndpointResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_replica_scaling_response import (  # noqa: E501
    V1OrganizationsServicesReplicaScalingResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_response import (
    V1OrganizationsServicesResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_response_1 import (
    V1OrganizationsServicesResponse1,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_response_2 import (
    V1OrganizationsServicesResponse2,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_response_4 import (
    V1OrganizationsServicesResponse4,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_scaling_response import (  # noqa: E501
    V1OrganizationsServicesScalingResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_scaling_schedule_response import (  # noqa: E501
    V1OrganizationsServicesScalingScheduleResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_scaling_schedule_response_2 import (  # noqa: E501
    V1OrganizationsServicesScalingScheduleResponse2,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_service_query_endpoint_response import (  # noqa: E501
    V1OrganizationsServicesServiceQueryEndpointResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_service_query_endpoint_response_1 import (  # noqa: E501
    V1OrganizationsServicesServiceQueryEndpointResponse1,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_state_response import (  # noqa: E501
    V1OrganizationsServicesStateResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_upgrade_window_response import (  # noqa: E501
    V1OrganizationsServicesUpgradeWindowResponse,
)
from openapispecforclickhousecloud.models.v_1_organizations_services_upgrade_window_response_2 import (  # noqa: E501
    V1OrganizationsServicesUpgradeWindowResponse2,
)


class ServiceApi(BaseApi):
    """A Controller to access Endpoints in the openapispecforclickhousecloud API."""

    def __init__(self, config):
        """Initialize ServiceApi object."""
        super(ServiceApi, self).__init__(config)

    def service_profiles_list(self,
                              organization_id,
                              region_id=None,
                              byoc_id=None):
        """Perform a GET request to
        /v1/organizations/{organizationId}/serviceProfiles.

        Returns the custom instance profiles the organization can use in a region.
        Pass byoc_id to list the profiles configured for a BYOC infrastructure; the
        region is then taken from the infrastructure and region_id may be omitted.
        The list is empty when the organization tier does not include custom hardware
        profiles.

        Args:
            organization_id (uuid|str): ID of the organization to list available
                profiles for.
            region_id (str, optional): Region to list profiles for, e.g. us-east-1.
                Required unless byoc_id is set; when both are set it must match the
                BYOC infrastructure's region.
            byoc_id (uuid|str, optional): ID of the BYOC infrastructure to list
                profiles for. BYOC profiles are only returned when this is set.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/serviceProfiles")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .query_param(Parameter()
                .key("region_id")
                .value(region_id))
            .query_param(Parameter()
                .key("byoc_id")
                .value(byoc_id))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServiceProfilesResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServiceProfiles400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServiceProfiles500ErrorException),
        ).execute()

    def instance_get_list(self,
                          organization_id,
                          filter=None):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services.

        Returns a list of all services in the organization.

        Args:
            organization_id (uuid|str): ID of the requested organization.
            filter (List[str], optional): Filter criteria to apply when retrieving
                the resource. Currently, only filtering by resource tags is supported.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .query_param(Parameter()
                .key("filter")
                .value(filter))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServices400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServices500ErrorException),
        ).execute()

    def instance_create(self,
                        organization_id,
                        body=None):
        """Perform a POST request to
        /v1/organizations/{organizationId}/services.

        Creates a new service in the organization, and returns the current service
        state and a password to access the service. The service is started
        asynchronously.

        Args:
            organization_id (uuid|str): ID of the organization that will own the
                service.
            body (ServicePostRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesResponse1.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServices400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServices500ErrorException),
        ).execute()

    def instance_get(self,
                     organization_id,
                     service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}.

        Returns a service that belongs to the organization

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the requested service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesResponse2.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServices400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServices500ErrorException),
        ).execute()

    def instance_update(self,
                        organization_id,
                        service_id,
                        body=None):
        """Perform a PATCH request to
        /v1/organizations/{organizationId}/services/{serviceId}.

        Updates basic service details like service name or IP access list.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service to update.
            body (ServicePatchRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesResponse2.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServices400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServices500ErrorException),
        ).execute()

    def instance_delete(self,
                        organization_id,
                        service_id):
        """Perform a DELETE request to
        /v1/organizations/{organizationId}/services/{serviceId}.

        Deletes the service. The service must be in stopped state and is deleted
        asynchronously after this method call.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service to delete.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesResponse4.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServices400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServices500ErrorException),
        ).execute()

    def instance_private_endpoint_config_get(self,
                                             organization_id,
                                             service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/privateEndpointConfig.

        Information required to set up a private endpoint

        Args:
            organization_id (uuid|str): ID of the requested organization.
            service_id (uuid|str): ID of the requested service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/privateEndpointConfig")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesPrivateEndpointConfigResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesPrivateEndpointConfig400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesPrivateEndpointConfig500ErrorException),
        ).execute()

    def instance_query_endpoint_get(self,
                                    organization_id,
                                    service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint.

        Get the configuration for the service query endpoint that allows executing
        queries via API.

        Args:
            organization_id (uuid|str): ID of the requested organization.
            service_id (uuid|str): ID of the requested service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesServiceQueryEndpointResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesServiceQueryEndpoint400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesServiceQueryEndpoint500ErrorException),
        ).execute()

    def instance_query_endpoint_delete(self,
                                       organization_id,
                                       service_id):
        """Perform a DELETE request to
        /v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint.

        Removes the service query endpoint.

        Args:
            organization_id (uuid|str): ID of the requested organization.
            service_id (uuid|str): ID of the requested service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesServiceQueryEndpointResponse1.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesServiceQueryEndpoint400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesServiceQueryEndpoint500ErrorException),
        ).execute()

    def instance_query_endpoint_upsert(self,
                                       organization_id,
                                       service_id,
                                       body=None):
        """Perform a POST request to
        /v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint.

        Create the service query endpoint that allows executing queries via API.

        Args:
            organization_id (uuid|str): ID of the requested organization.
            service_id (uuid|str): ID of the requested service.
            body (InstanceServiceQueryApiEndpointsPostRequest, optional): The request
                body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesServiceQueryEndpointResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesServiceQueryEndpoint400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesServiceQueryEndpoint500ErrorException),
        ).execute()

    def instance_state_update(self,
                              organization_id,
                              service_id,
                              body=None):
        """Perform a PATCH request to
        /v1/organizations/{organizationId}/services/{serviceId}/state.

        Starts, stops, or wakes a service. The `start` and `stop` commands require
        the `control-plane:service:manage` permission on the service. The `awake`
        command requires only `control-plane:service:view` and applies to an idle
        service; it does not start a stopped service.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service to update state.
            body (ServiceStatePatchRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/state")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesStateResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesState400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesState500ErrorException),
        ).execute()

    @deprecated()
    def instance_scaling_update(self,
                                organization_id,
                                service_id,
                                body=None):
        """Perform a PATCH request to
        /v1/organizations/{organizationId}/services/{serviceId}/scaling.

        Updates minimum and maximum total memory limits and idle mode scaling
        behavior for the service. The memory settings are available only for
        "production" services and must be a multiple of 12 starting from 24GB. Please
        contact support to enable adjustment of numReplicas.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service to update scaling parameters.
            body (ServiceScalingPatchRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/scaling")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesScalingResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesScaling400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesScaling500ErrorException),
        ).execute()

    def instance_replica_scaling_update(self,
                                        organization_id,
                                        service_id,
                                        body=None):
        """Perform a PATCH request to
        /v1/organizations/{organizationId}/services/{serviceId}/replicaScaling.

        Updates minimum and maximum memory limits per replica and idle mode scaling
        behavior for the service. Supports both vertical autoscaling (fixed replica
        count, variable memory) and horizontal autoscaling (variable replica count,
        fixed memory). The memory settings are available only for "production"
        services and must be a multiple of 4 starting from 8GB. For vertical
        autoscaling, please contact support to enable adjustment of numReplicas. For
        horizontal autoscaling (autoscalingMode "horizontal" with
        minReplicas/maxReplicas), contact support to enable the feature for your
        organization.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service to update scaling parameters.
            body (ServiceReplicaScalingPatchRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/replicaScaling")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesReplicaScalingResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesReplicaScaling400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesReplicaScaling500ErrorException),
        ).execute()

    def instance_password_update(self,
                                 organization_id,
                                 service_id,
                                 body=None):
        """Perform a PATCH request to
        /v1/organizations/{organizationId}/services/{serviceId}/password.

        Sets a new password for the service

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service to update password.
            body (ServicePasswordPatchRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/password")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesPasswordResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesPassword400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesPassword500ErrorException),
        ).execute()

    def instance_private_endpoint_create(self,
                                         organization_id,
                                         service_id,
                                         body=None):
        """Perform a POST request to
        /v1/organizations/{organizationId}/services/{serviceId}/privateEndpoint.

        Create a new private endpoint. The private endpoint will be associated with
        this service and organization

        Args:
            organization_id (uuid|str): ID of the requested organization.
            service_id (uuid|str): ID of the requested service.
            body (ServicPrivateEndpointePostRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/privateEndpoint")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesPrivateEndpointResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesPrivateEndpoint400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesPrivateEndpoint500ErrorException),
        ).execute()

    def scaling_schedule_get(self,
                             organization_id,
                             service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/scalingSchedule.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Returns the autoscaling schedule for a service. Returns 404 if
        no schedule has been configured or if the schedule was cleared. Requires the
        scheduled autoscaling feature to be enabled for the organization.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/scalingSchedule")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesScalingScheduleResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesScalingSchedule400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesScalingSchedule500ErrorException),
        ).execute()

    def scaling_schedule_upsert(self,
                                organization_id,
                                service_id,
                                body=None):
        """Perform a POST request to
        /v1/organizations/{organizationId}/services/{serviceId}/scalingSchedule.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Creates or fully replaces the autoscaling schedule for a
        service. Pass an empty `entries` array to clear the schedule — a subsequent
        GET will return 404, and the response will contain an empty `baseConfig` (all
        fields absent). The base scaling config (applied when no entry is active) is
        managed separately via the `replicaScaling` endpoint. Requires the scheduled
        autoscaling feature to be enabled for the organization.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.
            body (ScalingSchedulePostRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/scalingSchedule")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesScalingScheduleResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesScalingSchedule400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesScalingSchedule500ErrorException),
        ).execute()

    def scaling_schedule_delete(self,
                                organization_id,
                                service_id):
        """Perform a DELETE request to
        /v1/organizations/{organizationId}/services/{serviceId}/scalingSchedule.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Deletes the autoscaling schedule for a service. If a schedule
        entry is currently active, the base scaling config is restored to the
        instance before the schedule is removed. Returns 404 if no schedule exists.
        Requires the scheduled autoscaling feature to be enabled for the organization.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/scalingSchedule")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesScalingScheduleResponse2.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesScalingSchedule400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesScalingSchedule500ErrorException),
        ).execute()

    def upgrade_window_get(self,
                           organization_id,
                           service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/upgradeWindow.

        Returns the configured upgrade window for a service.
        Errors:
        - 401: missing, invalid, or disabled API key.
        - 403: caller lacks `control-plane:service:view` on the service.
        - 404: service does not exist, is not visible to the caller, or no upgrade
        window has been configured.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/upgradeWindow")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesUpgradeWindowResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesUpgradeWindow400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesUpgradeWindow500ErrorException),
        ).execute()

    def upgrade_window_update(self,
                              organization_id,
                              service_id,
                              body=None):
        """Perform a PUT request to
        /v1/organizations/{organizationId}/services/{serviceId}/upgradeWindow.

        Creates or fully replaces the upgrade window for a service. The upgrade
        window currently lasts 6 hours from `startHourUtc`. The upgrade window can
        only be set on primary services; secondary services inherit the primary
        service window.
        Errors:
        - 400: invalid field values (`weekday` not in 0–6, `startHourUtc` not in {0,
        6, 12, 18}), or the service is a secondary service.
        - 401: missing, invalid, or disabled API key.
        - 403: caller lacks `control-plane:service:manage` on the service, or the
        organization does not have the scheduled upgrades feature enabled.
        - 404: service does not exist or is not visible to the caller.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.
            body (UpgradeWindowPutRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/upgradeWindow")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesUpgradeWindowResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesUpgradeWindow400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesUpgradeWindow500ErrorException),
        ).execute()

    def upgrade_window_delete(self,
                              organization_id,
                              service_id):
        """Perform a DELETE request to
        /v1/organizations/{organizationId}/services/{serviceId}/upgradeWindow.

        Deletes the upgrade window for a service, restoring the default scheduling
        behaviour. The upgrade window can only be deleted on primary services.
        Deletion succeeds even if the organization has lost the scheduled upgrades
        entitlement, so a window can be cleared after entitlement loss.
        Errors:
        - 400: the service is a secondary service.
        - 401: missing, invalid, or disabled API key.
        - 403: caller lacks `control-plane:service:manage` on the service.
        - 404: service does not exist, is not visible to the caller, or no upgrade
        window is configured.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/upgradeWindow")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesUpgradeWindowResponse2.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesUpgradeWindow400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesUpgradeWindow500ErrorException),
        ).execute()

    def service_clickhouse_settings_list_get(self,
                                             organization_id,
                                             service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Returns the configured ClickHouse settings for the service. Only
        settings that have been explicitly set are included.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesClickhouseSettingsResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesClickhouseSettings400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesClickhouseSettings500ErrorException),
        ).execute()

    def service_clickhouse_settings_update(self,
                                           organization_id,
                                           service_id,
                                           body=None):
        """Perform a PATCH request to
        /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Updates one or more ClickHouse settings for the service. To
        reset a setting to its platform default, use the [DELETE single
        setting](#tag/Service/operation/serviceClickhouseSettingDelete) endpoint. Use
        the [schema
        endpoint](#tag/Service/operation/serviceClickhouseSettingsSchemaGet) to
        discover which settings are configurable.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.
            body (ServiceClickhouseSettingsPatchRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesClickhouseSettingsResponse1.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesClickhouseSettings400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesClickhouseSettings500ErrorException),
        ).execute()

    def service_clickhouse_settings_schema_get(self,
                                               organization_id,
                                               service_id):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/sche
        ma.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Returns the schema of all configurable ClickHouse settings,
        including types, valid values, descriptions, and warnings.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/schema")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesClickhouseSettingsSchemaResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesClickhouseSettingsSchema400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesClickhouseSettingsSchema500ErrorException),
        ).execute()

    def service_clickhouse_setting_get(self,
                                       organization_id,
                                       service_id,
                                       setting_name):
        """Perform a GET request to
        /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/{set
        tingName}.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Returns the current value of a ClickHouse setting for the
        service. Use the [schema
        endpoint](#tag/Service/operation/serviceClickhouseSettingsSchemaGet) to
        discover which settings are configurable.

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.
            setting_name (str): Name of the setting to retrieve.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/{settingName}")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("settingName")
                .value(setting_name)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesClickhouseSettingsSettingNameResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesClickhouseSettingsSettingName400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesClickhouseSettingsSettingName500ErrorException),
        ).execute()

    def service_clickhouse_setting_delete(self,
                                          organization_id,
                                          service_id,
                                          setting_name):
        """Perform a DELETE request to
        /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/{set
        tingName}.

        **Disclaimer:** This beta endpoint is evolving; the API contract may change.
        <br /><br /> Removes a previously-configured ClickHouse setting, reverting
        its effective value to the platform default. Settings under
        `spec.extraConfig.server.*` (e.g. `keep_alive_timeout`,
        `shared_merge_tree_disable_merges_and_mutations_assignment`) trigger a
        ClickHouse server rollout restart; other settings propagate to all replicas
        after a short delay. Deleting a setting that was never configured is a no-op
        (200 OK).

        Args:
            organization_id (uuid|str): ID of the organization that owns the service.
            service_id (uuid|str): ID of the service.
            setting_name (str): Name of the setting to reset.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/{settingName}")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("organizationId")
                .value(organization_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("serviceId")
                .value(service_id)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("settingName")
                .value(setting_name)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("basicAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(V1OrganizationsServicesClickhouseSettingsSettingNameResponse1.from_dictionary)
            .is_api_response(True)
            .local_error("400",
                "The request cannot be processed due to a client error. Please verify"
                " your request parameters and try again.",
                V1OrganizationsServicesClickhouseSettingsSettingName400ErrorException)
            .local_error("500",
                "An internal server error has occurred. If this issue persists, pleas"
                "e contact ClickHouse Cloud support for assistance.",
                V1OrganizationsServicesClickhouseSettingsSettingName500ErrorException),
        ).execute()
