from __future__ import annotations

from typing import TypeAlias

from ..click_stack_alert_channel_email import ClickStackAlertChannelEmail, ClickStackAlertChannelEmailDict
from ..click_stack_alert_channel_webhook import ClickStackAlertChannelWebhook, ClickStackAlertChannelWebhookDict

ClickStackAlertChannels: TypeAlias = ClickStackAlertChannelEmail | ClickStackAlertChannelWebhook

ClickStackAlertChannelsDict: TypeAlias = ClickStackAlertChannelEmailDict | ClickStackAlertChannelWebhookDict
