"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ActiveBalance(object):
    """Implementation of the 'ActiveBalance' model.

    Attributes:
        id (uuid|str): Unique ID of the prepaid balance.
        remaining_prepaid_credits (float): Remaining credits available on this
            balance, in ClickHouse Credits (CHCs).
        total_amount (float): Total credits granted on this balance, in ClickHouse
            Credits (CHCs).
        amount_spent (float): Credits spent from this balance, in ClickHouse Credits
            (CHCs).
        start_date (datetime): Date the balance became active. ISO-8601, based on the
            UTC timezone.
        expiration_date (datetime): Date the balance expires. ISO-8601, based on the
            UTC timezone.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "remaining_prepaid_credits": "remainingPrepaidCredits",
        "total_amount": "totalAmount",
        "amount_spent": "amountSpent",
        "start_date": "startDate",
        "expiration_date": "expirationDate",
    }

    _optionals = [
        "id",
        "remaining_prepaid_credits",
        "total_amount",
        "amount_spent",
        "start_date",
        "expiration_date",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        remaining_prepaid_credits=APIHelper.SKIP,
        total_amount=APIHelper.SKIP,
        amount_spent=APIHelper.SKIP,
        start_date=APIHelper.SKIP,
        expiration_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ActiveBalance instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if remaining_prepaid_credits is not APIHelper.SKIP:
            self.remaining_prepaid_credits = remaining_prepaid_credits
        if total_amount is not APIHelper.SKIP:
            self.total_amount = total_amount
        if amount_spent is not APIHelper.SKIP:
            self.amount_spent = amount_spent
        if start_date is not APIHelper.SKIP:
            self.start_date =\
                 APIHelper.apply_datetime_converter(
                start_date, APIHelper.RFC3339DateTime)\
                 if start_date else None
        if expiration_date is not APIHelper.SKIP:
            self.expiration_date =\
                 APIHelper.apply_datetime_converter(
                expiration_date, APIHelper.RFC3339DateTime)\
                 if expiration_date else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        remaining_prepaid_credits =\
            dictionary.get("remainingPrepaidCredits")\
            if dictionary.get("remainingPrepaidCredits")\
                else APIHelper.SKIP
        total_amount =\
            dictionary.get("totalAmount")\
            if dictionary.get("totalAmount")\
                else APIHelper.SKIP
        amount_spent =\
            dictionary.get("amountSpent")\
            if dictionary.get("amountSpent")\
                else APIHelper.SKIP
        start_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("startDate")).datetime\
            if dictionary.get("startDate") else APIHelper.SKIP
        expiration_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expirationDate")).datetime\
            if dictionary.get("expirationDate") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   remaining_prepaid_credits,
                   total_amount,
                   amount_spent,
                   start_date,
                   expiration_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _remaining_prepaid_credits=(
            self.remaining_prepaid_credits
            if hasattr(self, "remaining_prepaid_credits")
            else None
        )
        _total_amount=(
            self.total_amount
            if hasattr(self, "total_amount")
            else None
        )
        _amount_spent=(
            self.amount_spent
            if hasattr(self, "amount_spent")
            else None
        )
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _expiration_date=(
            self.expiration_date
            if hasattr(self, "expiration_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"remaining_prepaid_credits={_remaining_prepaid_credits!r}, "
            f"total_amount={_total_amount!r}, "
            f"amount_spent={_amount_spent!r}, "
            f"start_date={_start_date!r}, "
            f"expiration_date={_expiration_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _remaining_prepaid_credits=(
            self.remaining_prepaid_credits
            if hasattr(self, "remaining_prepaid_credits")
            else None
        )
        _total_amount=(
            self.total_amount
            if hasattr(self, "total_amount")
            else None
        )
        _amount_spent=(
            self.amount_spent
            if hasattr(self, "amount_spent")
            else None
        )
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _expiration_date=(
            self.expiration_date
            if hasattr(self, "expiration_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"remaining_prepaid_credits={_remaining_prepaid_credits!s}, "
            f"total_amount={_total_amount!s}, "
            f"amount_spent={_amount_spent!s}, "
            f"start_date={_start_date!s}, "
            f"expiration_date={_expiration_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
