"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class Activity(object):
    """Implementation of the 'Activity' model.

    Attributes:
        id (str): Unique activity ID.
        created_at (datetime): Timestamp of the activity. ISO-8601.
        mtype (Type12): Type of the activity.
        actor_type (ActorType): Type of the actor: 'user', 'support', 'system', 'api'.
        actor_id (str): Unique actor ID.
        actor_details (str): Additional information about the actor.
        actor_ip_address (str): IP address of the actor. Defined for 'user' and 'api'
            actor types.
        organization_id (str): Scope of the activity: organization ID this activity
            is related to.
        service_id (str): Scope of the activity: service ID this activity is related
            to.
        user_agent (str): User agent of the actor
        target_key_id (str): For 'openapi_key_update' activities: the ID of the API
            key that was updated.
        key_update_type (KeyUpdateType): For 'openapi_key_update' activities: the
            type of update that was performed.
        target_role_ids (List[str]): For role and actor-role activities: IDs of the
            affected roles.
        target_role_names (List[str]): For role and actor-role activities: names of
            the affected roles, when recorded.
        target_actor_ids (List[str]): For 'organization_member_update_roles' and
            'organization_member_remove_roles' activities: IDs of the affected actors
            (e.g. 'user/<id>').
        target_resource_ids (List[str]): For 'role_resources_delete' activities: IDs
            of the deleted resources the roles referenced.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "created_at": "createdAt",
        "mtype": "type",
        "actor_type": "actorType",
        "actor_id": "actorId",
        "actor_details": "actorDetails",
        "actor_ip_address": "actorIpAddress",
        "organization_id": "organizationId",
        "service_id": "serviceId",
        "user_agent": "userAgent",
        "target_key_id": "targetKeyId",
        "key_update_type": "keyUpdateType",
        "target_role_ids": "targetRoleIds",
        "target_role_names": "targetRoleNames",
        "target_actor_ids": "targetActorIds",
        "target_resource_ids": "targetResourceIds",
    }

    _optionals = [
        "id",
        "created_at",
        "mtype",
        "actor_type",
        "actor_id",
        "actor_details",
        "actor_ip_address",
        "organization_id",
        "service_id",
        "user_agent",
        "target_key_id",
        "key_update_type",
        "target_role_ids",
        "target_role_names",
        "target_actor_ids",
        "target_resource_ids",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        actor_type=APIHelper.SKIP,
        actor_id=APIHelper.SKIP,
        actor_details=APIHelper.SKIP,
        actor_ip_address=APIHelper.SKIP,
        organization_id=APIHelper.SKIP,
        service_id=APIHelper.SKIP,
        user_agent=APIHelper.SKIP,
        target_key_id=APIHelper.SKIP,
        key_update_type=APIHelper.SKIP,
        target_role_ids=APIHelper.SKIP,
        target_role_names=APIHelper.SKIP,
        target_actor_ids=APIHelper.SKIP,
        target_resource_ids=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Activity instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if actor_type is not APIHelper.SKIP:
            self.actor_type = actor_type
        if actor_id is not APIHelper.SKIP:
            self.actor_id = actor_id
        if actor_details is not APIHelper.SKIP:
            self.actor_details = actor_details
        if actor_ip_address is not APIHelper.SKIP:
            self.actor_ip_address = actor_ip_address
        if organization_id is not APIHelper.SKIP:
            self.organization_id = organization_id
        if service_id is not APIHelper.SKIP:
            self.service_id = service_id
        if user_agent is not APIHelper.SKIP:
            self.user_agent = user_agent
        if target_key_id is not APIHelper.SKIP:
            self.target_key_id = target_key_id
        if key_update_type is not APIHelper.SKIP:
            self.key_update_type = key_update_type
        if target_role_ids is not APIHelper.SKIP:
            self.target_role_ids = target_role_ids
        if target_role_names is not APIHelper.SKIP:
            self.target_role_names = target_role_names
        if target_actor_ids is not APIHelper.SKIP:
            self.target_actor_ids = target_actor_ids
        if target_resource_ids is not APIHelper.SKIP:
            self.target_resource_ids = target_resource_ids

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("createdAt")).datetime\
            if dictionary.get("createdAt") else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        actor_type =\
            dictionary.get("actorType")\
            if dictionary.get("actorType")\
                else APIHelper.SKIP
        actor_id =\
            dictionary.get("actorId")\
            if dictionary.get("actorId")\
                else APIHelper.SKIP
        actor_details =\
            dictionary.get("actorDetails")\
            if dictionary.get("actorDetails")\
                else APIHelper.SKIP
        actor_ip_address =\
            dictionary.get("actorIpAddress")\
            if dictionary.get("actorIpAddress")\
                else APIHelper.SKIP
        organization_id =\
            dictionary.get("organizationId")\
            if dictionary.get("organizationId")\
                else APIHelper.SKIP
        service_id =\
            dictionary.get("serviceId")\
            if dictionary.get("serviceId")\
                else APIHelper.SKIP
        user_agent =\
            dictionary.get("userAgent")\
            if dictionary.get("userAgent")\
                else APIHelper.SKIP
        target_key_id =\
            dictionary.get("targetKeyId")\
            if dictionary.get("targetKeyId")\
                else APIHelper.SKIP
        key_update_type =\
            dictionary.get("keyUpdateType")\
            if dictionary.get("keyUpdateType")\
                else APIHelper.SKIP
        target_role_ids =\
            dictionary.get("targetRoleIds")\
            if dictionary.get("targetRoleIds")\
                else APIHelper.SKIP
        target_role_names =\
            dictionary.get("targetRoleNames")\
            if dictionary.get("targetRoleNames")\
                else APIHelper.SKIP
        target_actor_ids =\
            dictionary.get("targetActorIds")\
            if dictionary.get("targetActorIds")\
                else APIHelper.SKIP
        target_resource_ids =\
            dictionary.get("targetResourceIds")\
            if dictionary.get("targetResourceIds")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   created_at,
                   mtype,
                   actor_type,
                   actor_id,
                   actor_details,
                   actor_ip_address,
                   organization_id,
                   service_id,
                   user_agent,
                   target_key_id,
                   key_update_type,
                   target_role_ids,
                   target_role_names,
                   target_actor_ids,
                   target_resource_ids,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _actor_type=(
            self.actor_type
            if hasattr(self, "actor_type")
            else None
        )
        _actor_id=(
            self.actor_id
            if hasattr(self, "actor_id")
            else None
        )
        _actor_details=(
            self.actor_details
            if hasattr(self, "actor_details")
            else None
        )
        _actor_ip_address=(
            self.actor_ip_address
            if hasattr(self, "actor_ip_address")
            else None
        )
        _organization_id=(
            self.organization_id
            if hasattr(self, "organization_id")
            else None
        )
        _service_id=(
            self.service_id
            if hasattr(self, "service_id")
            else None
        )
        _user_agent=(
            self.user_agent
            if hasattr(self, "user_agent")
            else None
        )
        _target_key_id=(
            self.target_key_id
            if hasattr(self, "target_key_id")
            else None
        )
        _key_update_type=(
            self.key_update_type
            if hasattr(self, "key_update_type")
            else None
        )
        _target_role_ids=(
            self.target_role_ids
            if hasattr(self, "target_role_ids")
            else None
        )
        _target_role_names=(
            self.target_role_names
            if hasattr(self, "target_role_names")
            else None
        )
        _target_actor_ids=(
            self.target_actor_ids
            if hasattr(self, "target_actor_ids")
            else None
        )
        _target_resource_ids=(
            self.target_resource_ids
            if hasattr(self, "target_resource_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"created_at={_created_at!r}, "
            f"mtype={_mtype!r}, "
            f"actor_type={_actor_type!r}, "
            f"actor_id={_actor_id!r}, "
            f"actor_details={_actor_details!r}, "
            f"actor_ip_address={_actor_ip_address!r}, "
            f"organization_id={_organization_id!r}, "
            f"service_id={_service_id!r}, "
            f"user_agent={_user_agent!r}, "
            f"target_key_id={_target_key_id!r}, "
            f"key_update_type={_key_update_type!r}, "
            f"target_role_ids={_target_role_ids!r}, "
            f"target_role_names={_target_role_names!r}, "
            f"target_actor_ids={_target_actor_ids!r}, "
            f"target_resource_ids={_target_resource_ids!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _actor_type=(
            self.actor_type
            if hasattr(self, "actor_type")
            else None
        )
        _actor_id=(
            self.actor_id
            if hasattr(self, "actor_id")
            else None
        )
        _actor_details=(
            self.actor_details
            if hasattr(self, "actor_details")
            else None
        )
        _actor_ip_address=(
            self.actor_ip_address
            if hasattr(self, "actor_ip_address")
            else None
        )
        _organization_id=(
            self.organization_id
            if hasattr(self, "organization_id")
            else None
        )
        _service_id=(
            self.service_id
            if hasattr(self, "service_id")
            else None
        )
        _user_agent=(
            self.user_agent
            if hasattr(self, "user_agent")
            else None
        )
        _target_key_id=(
            self.target_key_id
            if hasattr(self, "target_key_id")
            else None
        )
        _key_update_type=(
            self.key_update_type
            if hasattr(self, "key_update_type")
            else None
        )
        _target_role_ids=(
            self.target_role_ids
            if hasattr(self, "target_role_ids")
            else None
        )
        _target_role_names=(
            self.target_role_names
            if hasattr(self, "target_role_names")
            else None
        )
        _target_actor_ids=(
            self.target_actor_ids
            if hasattr(self, "target_actor_ids")
            else None
        )
        _target_resource_ids=(
            self.target_resource_ids
            if hasattr(self, "target_resource_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"created_at={_created_at!s}, "
            f"mtype={_mtype!s}, "
            f"actor_type={_actor_type!s}, "
            f"actor_id={_actor_id!s}, "
            f"actor_details={_actor_details!s}, "
            f"actor_ip_address={_actor_ip_address!s}, "
            f"organization_id={_organization_id!s}, "
            f"service_id={_service_id!s}, "
            f"user_agent={_user_agent!s}, "
            f"target_key_id={_target_key_id!s}, "
            f"key_update_type={_key_update_type!s}, "
            f"target_role_ids={_target_role_ids!s}, "
            f"target_role_names={_target_role_names!s}, "
            f"target_actor_ids={_target_actor_ids!s}, "
            f"target_resource_ids={_target_resource_ids!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
