"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ApiKeyHashData(object):
    """Implementation of the 'ApiKeyHashData' model.

    Attributes:
        key_id_hash (str): Hash of the key ID.
        key_id_suffix (str): Last 4 digits of the key ID. Algorithm: echo -n
            "yourpassword" | sha256sum | tr -d '-' | xxd -r -p | base64
        key_secret_hash (str): Hash of the key secret. Algorithm: echo -n
            "yourpassword" | sha256sum | tr -d '-' | xxd -r -p | base64
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key_id_hash": "keyIdHash",
        "key_id_suffix": "keyIdSuffix",
        "key_secret_hash": "keySecretHash",
    }

    _optionals = [
        "key_id_hash",
        "key_id_suffix",
        "key_secret_hash",
    ]

    def __init__(
        self,
        key_id_hash=APIHelper.SKIP,
        key_id_suffix=APIHelper.SKIP,
        key_secret_hash=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ApiKeyHashData instance."""
        # Initialize members of the class
        if key_id_hash is not APIHelper.SKIP:
            self.key_id_hash = key_id_hash
        if key_id_suffix is not APIHelper.SKIP:
            self.key_id_suffix = key_id_suffix
        if key_secret_hash is not APIHelper.SKIP:
            self.key_secret_hash = key_secret_hash

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        key_id_hash =\
            dictionary.get("keyIdHash")\
            if dictionary.get("keyIdHash")\
                else APIHelper.SKIP
        key_id_suffix =\
            dictionary.get("keyIdSuffix")\
            if dictionary.get("keyIdSuffix")\
                else APIHelper.SKIP
        key_secret_hash =\
            dictionary.get("keySecretHash")\
            if dictionary.get("keySecretHash")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(key_id_hash,
                   key_id_suffix,
                   key_secret_hash,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _key_id_hash=(
            self.key_id_hash
            if hasattr(self, "key_id_hash")
            else None
        )
        _key_id_suffix=(
            self.key_id_suffix
            if hasattr(self, "key_id_suffix")
            else None
        )
        _key_secret_hash=(
            self.key_secret_hash
            if hasattr(self, "key_secret_hash")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key_id_hash={_key_id_hash!r}, "
            f"key_id_suffix={_key_id_suffix!r}, "
            f"key_secret_hash={_key_secret_hash!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _key_id_hash=(
            self.key_id_hash
            if hasattr(self, "key_id_hash")
            else None
        )
        _key_id_suffix=(
            self.key_id_suffix
            if hasattr(self, "key_id_suffix")
            else None
        )
        _key_secret_hash=(
            self.key_secret_hash
            if hasattr(self, "key_secret_hash")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key_id_hash={_key_id_hash!s}, "
            f"key_id_suffix={_key_id_suffix!s}, "
            f"key_secret_hash={_key_secret_hash!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
