"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class AssignedRole(object):
    """Implementation of the 'AssignedRole' model.

    Attributes:
        role_id (uuid|str): Unique identifier of the role
        role_name (str): Human-readable name of the role
        role_type (RoleType): Type of role: system (predefined) or custom
            (organization-defined)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "role_id": "roleId",
        "role_name": "roleName",
        "role_type": "roleType",
    }

    _optionals = [
        "role_id",
        "role_name",
        "role_type",
    ]

    def __init__(
        self,
        role_id=APIHelper.SKIP,
        role_name=APIHelper.SKIP,
        role_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AssignedRole instance."""
        # Initialize members of the class
        if role_id is not APIHelper.SKIP:
            self.role_id = role_id
        if role_name is not APIHelper.SKIP:
            self.role_name = role_name
        if role_type is not APIHelper.SKIP:
            self.role_type = role_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        role_id =\
            dictionary.get("roleId")\
            if dictionary.get("roleId")\
                else APIHelper.SKIP
        role_name =\
            dictionary.get("roleName")\
            if dictionary.get("roleName")\
                else APIHelper.SKIP
        role_type =\
            dictionary.get("roleType")\
            if dictionary.get("roleType")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(role_id,
                   role_name,
                   role_type,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _role_id=(
            self.role_id
            if hasattr(self, "role_id")
            else None
        )
        _role_name=(
            self.role_name
            if hasattr(self, "role_name")
            else None
        )
        _role_type=(
            self.role_type
            if hasattr(self, "role_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"role_id={_role_id!r}, "
            f"role_name={_role_name!r}, "
            f"role_type={_role_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _role_id=(
            self.role_id
            if hasattr(self, "role_id")
            else None
        )
        _role_name=(
            self.role_name
            if hasattr(self, "role_name")
            else None
        )
        _role_type=(
            self.role_type
            if hasattr(self, "role_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"role_id={_role_id!s}, "
            f"role_name={_role_name!s}, "
            f"role_type={_role_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
