"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickStackEventPatternsChartConfig(object):
    """Implementation of the 'ClickStackEventPatternsChartConfig' model.

    Attributes:
        display_type (str): Display type discriminator. Must be "event_patterns" for
            pattern mining tiles.
        source_id (str): ID of the data source to mine patterns from.
        select (str): Column or expression to mine patterns from. Leave empty to use
            the source default (Body for logs, SpanName for traces).
        where (str): Filter condition for the pattern mining query (syntax depends on
            whereLanguage).
        where_language (WhereLanguage4): Query language for the where clause.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "display_type": "displayType",
        "source_id": "sourceId",
        "select": "select",
        "where": "where",
        "where_language": "whereLanguage",
    }

    _optionals = [
        "select",
        "where",
        "where_language",
    ]

    def __init__(
        self,
        source_id=None,
        select=APIHelper.SKIP,
        where=APIHelper.SKIP,
        where_language=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackEventPatternsChartConfig instance."""
        # Initialize members of the class
        self.display_type = "event_patterns"
        self.source_id = source_id
        if select is not APIHelper.SKIP:
            self.select = select
        if where is not APIHelper.SKIP:
            self.where = where
        if where_language is not APIHelper.SKIP:
            self.where_language = where_language

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        source_id =\
            dictionary.get("sourceId")\
            if dictionary.get("sourceId")\
                else None
        select =\
            dictionary.get("select")\
            if dictionary.get("select")\
                else APIHelper.SKIP
        where =\
            dictionary.get("where")\
            if dictionary.get("where")\
                else APIHelper.SKIP
        where_language =\
            dictionary.get("whereLanguage")\
            if dictionary.get("whereLanguage")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(source_id,
                   select,
                   where,
                   where_language,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.display_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.source_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("displayType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("sourceId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _display_type=self.display_type
        _source_id=self.source_id
        _select=(
            self.select
            if hasattr(self, "select")
            else None
        )
        _where=(
            self.where
            if hasattr(self, "where")
            else None
        )
        _where_language=(
            self.where_language
            if hasattr(self, "where_language")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"display_type={_display_type!r}, "
            f"source_id={_source_id!r}, "
            f"select={_select!r}, "
            f"where={_where!r}, "
            f"where_language={_where_language!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _display_type=self.display_type
        _source_id=self.source_id
        _select=(
            self.select
            if hasattr(self, "select")
            else None
        )
        _where=(
            self.where
            if hasattr(self, "where")
            else None
        )
        _where_language=(
            self.where_language
            if hasattr(self, "where_language")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"display_type={_display_type!s}, "
            f"source_id={_source_id!s}, "
            f"select={_select!s}, "
            f"where={_where!s}, "
            f"where_language={_where_language!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
