"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.where_language import (
    WhereLanguage,
)


class ClickStackSearchChartSeries(object):
    """Implementation of the 'ClickStackSearchChartSeries' model.

    Attributes:
        mtype (str): Series type discriminator. Must be "search" for search/log
            viewer charts.
        source_id (str): ID of the data source to query
        fields (List[str]): List of field names to display in the search results table
        where (str): Filter query for the data (syntax depends on whereLanguage)
        where_language (WhereLanguage): Query language for the where clause
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "source_id": "sourceId",
        "fields": "fields",
        "where": "where",
        "where_language": "whereLanguage",
    }

    def __init__(
        self,
        source_id=None,
        fields=None,
        where=None,
        where_language=None,
        additional_properties=None):
        """Initialize a ClickStackSearchChartSeries instance."""
        # Initialize members of the class
        self.mtype = "search"
        self.source_id = source_id
        self.fields = fields
        self.where = where
        self.where_language = where_language

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        source_id =\
            dictionary.get("sourceId")\
            if dictionary.get("sourceId")\
                else None
        fields =\
            dictionary.get("fields")\
            if dictionary.get("fields")\
                else None
        where =\
            dictionary.get("where")\
            if dictionary.get("where")\
                else None
        where_language =\
            dictionary.get("whereLanguage")\
            if dictionary.get("whereLanguage")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(source_id,
                   fields,
                   where,
                   where_language,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.source_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.fields,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.where,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.where_language,
                    type_callable=lambda value:
                        WhereLanguage.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("sourceId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("fields"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("where"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("whereLanguage"),
                type_callable=lambda value:
                    WhereLanguage.validate(value))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _source_id=self.source_id
        _fields=self.fields
        _where=self.where
        _where_language=self.where_language
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"source_id={_source_id!r}, "
            f"fields={_fields!r}, "
            f"where={_where!r}, "
            f"where_language={_where_language!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _source_id=self.source_id
        _fields=self.fields
        _where=self.where
        _where_language=self.where_language
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"source_id={_source_id!s}, "
            f"fields={_fields!s}, "
            f"where={_where!s}, "
            f"where_language={_where_language!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
