"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_pipe_big_query_pipe_settings import (
    ClickPipeBigQueryPipeSettings,
)
from openapispecforclickhousecloud.models.click_pipe_big_query_pipe_table_mapping import (  # noqa: E501
    ClickPipeBigQueryPipeTableMapping,
)


class ClickPipeBigQueryWorkloadIdentitySource(object):
    """Implementation of the 'ClickPipeBigQueryWorkloadIdentitySource' model.

    Attributes:
        snapshot_staging_path (str): GCS bucket path for staging snapshot data (e.g.,
            gs://my-bucket/staging/). Data will be automatically cleaned up after
            initial load.
        settings (ClickPipeBigQueryPipeSettings): The model property of type
            ClickPipeBigQueryPipeSettings.
        table_mappings (List[ClickPipeBigQueryPipeTableMapping]): Table mappings for
            BigQuery pipe.
        authentication (str): Authenticated with the ClickPipes service tenant
            identity. SERVICE_ACCOUNT_WORKLOAD_IDENTITY is in Private Preview.
            ClickPipes uses the GCP service account returned in
            gcpWorkloadIdentity.principal by the operation with operationId
            clickPipesServiceContextGet; grant it access to the source resources.
        project_id (str): GCP project ID that owns the BigQuery resources. Older
            pipes created outside OpenAPI may omit this field.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "snapshot_staging_path": "snapshotStagingPath",
        "settings": "settings",
        "table_mappings": "tableMappings",
        "authentication": "authentication",
        "project_id": "projectId",
    }

    _optionals = [
        "project_id",
    ]

    def __init__(
        self,
        snapshot_staging_path=None,
        settings=None,
        table_mappings=None,
        project_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipeBigQueryWorkloadIdentitySource instance."""
        # Initialize members of the class
        self.snapshot_staging_path = snapshot_staging_path
        self.settings = settings
        self.table_mappings = table_mappings
        self.authentication = "SERVICE_ACCOUNT_WORKLOAD_IDENTITY"
        if project_id is not APIHelper.SKIP:
            self.project_id = project_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        snapshot_staging_path =\
            dictionary.get("snapshotStagingPath")\
            if dictionary.get("snapshotStagingPath")\
                else None
        settings =\
            ClickPipeBigQueryPipeSettings.from_dictionary(
                dictionary.get("settings"))\
                if dictionary.get("settings") else None
        table_mappings = None
        if dictionary.get("tableMappings") is not None:
            table_mappings = [
                ClickPipeBigQueryPipeTableMapping.from_dictionary(x)
                    for x in dictionary.get("tableMappings")
            ]
        project_id =\
            dictionary.get("projectId")\
            if dictionary.get("projectId")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(snapshot_staging_path,
                   settings,
                   table_mappings,
                   project_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _snapshot_staging_path=self.snapshot_staging_path
        _settings=self.settings
        _table_mappings=self.table_mappings
        _authentication=self.authentication
        _project_id=(
            self.project_id
            if hasattr(self, "project_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"snapshot_staging_path={_snapshot_staging_path!r}, "
            f"settings={_settings!r}, "
            f"table_mappings={_table_mappings!r}, "
            f"authentication={_authentication!r}, "
            f"project_id={_project_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _snapshot_staging_path=self.snapshot_staging_path
        _settings=self.settings
        _table_mappings=self.table_mappings
        _authentication=self.authentication
        _project_id=(
            self.project_id
            if hasattr(self, "project_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"snapshot_staging_path={_snapshot_staging_path!s}, "
            f"settings={_settings!s}, "
            f"table_mappings={_table_mappings!s}, "
            f"authentication={_authentication!s}, "
            f"project_id={_project_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
