"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_pipe_schema_discovery_field import (
    ClickPipeSchemaDiscoveryField,
)


class ClickPipeSchemaDiscoveryResponse(object):
    """Implementation of the 'ClickPipeSchemaDiscoveryResponse' model.

    Attributes:
        fields (List[ClickPipeSchemaDiscoveryField]): Inferred schema fields with
            their ClickHouse data types.
        meta (Dict[str, str]): The model property of type Dict[str, str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fields": "fields",
        "meta": "meta",
    }

    _optionals = [
        "fields",
        "meta",
    ]

    _nullables = [
        "meta",
    ]

    def __init__(
        self,
        fields=APIHelper.SKIP,
        meta=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipeSchemaDiscoveryResponse instance."""
        # Initialize members of the class
        if fields is not APIHelper.SKIP:
            self.fields = fields
        if meta is not APIHelper.SKIP:
            self.meta = meta

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        fields = None
        if dictionary.get("fields") is not None:
            fields = [
                ClickPipeSchemaDiscoveryField.from_dictionary(x)
                    for x in dictionary.get("fields")
            ]
        else:
            fields = APIHelper.SKIP
        meta =\
            dictionary.get("meta")\
            if "meta" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(fields,
                   meta,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _meta=(
            self.meta
            if hasattr(self, "meta")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"fields={_fields!r}, "
            f"meta={_meta!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _meta=(
            self.meta
            if hasattr(self, "meta")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"fields={_fields!s}, "
            f"meta={_meta!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
