"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickPipePatchPostgresPipeRemoveTableMapping(object):
    """Implementation of the 'ClickPipePatchPostgresPipeRemoveTableMapping' model.

    Attributes:
        source_schema_name (str): PostgreSQL source schema name.
        source_table (str): PostgreSQL source table name.
        target_table (str): ClickHouse target table name, optionally prefixed with
            schema name (e.g., "my_schema_my_table"). The table will be created
            automatically if it does not exist. For snapshot mode, the target table
            must be empty.
        table_engine (TableEngine): ClickHouse table engine: "ReplacingMergeTree"
            (handles updates/deletes), "MergeTree" (append-only), or "Null" (forward
            data to materialized views without storing it).
        partition_key (str): Custom partitioning column used for parallel
            snapshotting. Only beneficial for PostgreSQL 13 (no benefit for PG14+,
            which supports indexed ctid scans). Must be an indexed column of type:
            `smallint`, `integer`, `bigint`, `timestamp without time zone`, or
            `timestamp with time zone`. Unrelated to ClickHouse partitioning.
        partition_by_expr (str): ClickHouse PARTITION BY expression applied to the
            destination table when ClickPipes creates it.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "source_schema_name": "sourceSchemaName",
        "source_table": "sourceTable",
        "target_table": "targetTable",
        "table_engine": "tableEngine",
        "partition_key": "partitionKey",
        "partition_by_expr": "partitionByExpr",
    }

    _optionals = [
        "source_schema_name",
        "source_table",
        "target_table",
        "table_engine",
        "partition_key",
        "partition_by_expr",
    ]

    _nullables = [
        "source_schema_name",
        "source_table",
        "target_table",
        "table_engine",
        "partition_key",
        "partition_by_expr",
    ]

    def __init__(
        self,
        source_schema_name=APIHelper.SKIP,
        source_table=APIHelper.SKIP,
        target_table=APIHelper.SKIP,
        table_engine=APIHelper.SKIP,
        partition_key=APIHelper.SKIP,
        partition_by_expr=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipePatchPostgresPipeRemoveTableMapping instance."""
        # Initialize members of the class
        if source_schema_name is not APIHelper.SKIP:
            self.source_schema_name = source_schema_name
        if source_table is not APIHelper.SKIP:
            self.source_table = source_table
        if target_table is not APIHelper.SKIP:
            self.target_table = target_table
        if table_engine is not APIHelper.SKIP:
            self.table_engine = table_engine
        if partition_key is not APIHelper.SKIP:
            self.partition_key = partition_key
        if partition_by_expr is not APIHelper.SKIP:
            self.partition_by_expr = partition_by_expr

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        source_schema_name =\
            dictionary.get("sourceSchemaName")\
            if "sourceSchemaName" in dictionary.keys()\
                else APIHelper.SKIP
        source_table =\
            dictionary.get("sourceTable")\
            if "sourceTable" in dictionary.keys()\
                else APIHelper.SKIP
        target_table =\
            dictionary.get("targetTable")\
            if "targetTable" in dictionary.keys()\
                else APIHelper.SKIP
        table_engine =\
            dictionary.get("tableEngine")\
            if "tableEngine" in dictionary.keys()\
                else APIHelper.SKIP
        partition_key =\
            dictionary.get("partitionKey")\
            if "partitionKey" in dictionary.keys()\
                else APIHelper.SKIP
        partition_by_expr =\
            dictionary.get("partitionByExpr")\
            if "partitionByExpr" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(source_schema_name,
                   source_table,
                   target_table,
                   table_engine,
                   partition_key,
                   partition_by_expr,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _source_schema_name=(
            self.source_schema_name
            if hasattr(self, "source_schema_name")
            else None
        )
        _source_table=(
            self.source_table
            if hasattr(self, "source_table")
            else None
        )
        _target_table=(
            self.target_table
            if hasattr(self, "target_table")
            else None
        )
        _table_engine=(
            self.table_engine
            if hasattr(self, "table_engine")
            else None
        )
        _partition_key=(
            self.partition_key
            if hasattr(self, "partition_key")
            else None
        )
        _partition_by_expr=(
            self.partition_by_expr
            if hasattr(self, "partition_by_expr")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"source_schema_name={_source_schema_name!r}, "
            f"source_table={_source_table!r}, "
            f"target_table={_target_table!r}, "
            f"table_engine={_table_engine!r}, "
            f"partition_key={_partition_key!r}, "
            f"partition_by_expr={_partition_by_expr!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _source_schema_name=(
            self.source_schema_name
            if hasattr(self, "source_schema_name")
            else None
        )
        _source_table=(
            self.source_table
            if hasattr(self, "source_table")
            else None
        )
        _target_table=(
            self.target_table
            if hasattr(self, "target_table")
            else None
        )
        _table_engine=(
            self.table_engine
            if hasattr(self, "table_engine")
            else None
        )
        _partition_key=(
            self.partition_key
            if hasattr(self, "partition_key")
            else None
        )
        _partition_by_expr=(
            self.partition_by_expr
            if hasattr(self, "partition_by_expr")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"source_schema_name={_source_schema_name!s}, "
            f"source_table={_source_table!s}, "
            f"target_table={_target_table!s}, "
            f"table_engine={_table_engine!s}, "
            f"partition_key={_partition_key!s}, "
            f"partition_by_expr={_partition_by_expr!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
