"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickStackSourceFrom(object):
    """Implementation of the 'ClickStackSourceFrom' model.

    Attributes:
        database_name (str): ClickHouse database name
        table_name (str): ClickHouse table name
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "database_name": "databaseName",
        "table_name": "tableName",
    }

    def __init__(
        self,
        database_name=None,
        table_name=None,
        additional_properties=None):
        """Initialize a ClickStackSourceFrom instance."""
        # Initialize members of the class
        self.database_name = database_name
        self.table_name = table_name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        database_name =\
            dictionary.get("databaseName")\
            if dictionary.get("databaseName")\
                else None
        table_name =\
            dictionary.get("tableName")\
            if dictionary.get("tableName")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(database_name,
                   table_name,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.database_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.table_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("databaseName"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("tableName"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _database_name=self.database_name
        _table_name=self.table_name
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"database_name={_database_name!r}, "
            f"table_name={_table_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _database_name=self.database_name
        _table_name=self.table_name
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"database_name={_database_name!s}, "
            f"table_name={_table_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
