"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.agg_fn import (
    AggFn,
)
from openapispecforclickhousecloud.models.click_stack_number_format import (
    ClickStackNumberFormat,
)
from openapispecforclickhousecloud.models.where_language import (
    WhereLanguage,
)


class ClickStackTimeChartSeries(object):
    """Implementation of the 'ClickStackTimeChartSeries' model.

    Attributes:
        mtype (str): Series type discriminator. Must be "time" for time-series charts.
        source_id (str): ID of the data source to query
        agg_fn (AggFn): Aggregation function to apply to the field or metric value
        level (float): Percentile level for quantile aggregations (e.g., 0.95 for p95)
        field (str): Column or expression to aggregate (required for most aggregation
            functions except count)
        alias (str): Display name for the series in the chart
        where (str): Filter query for the data (syntax depends on whereLanguage)
        where_language (WhereLanguage): Query language for the where clause
        group_by (List[str]): Fields to group results by (creates separate series for
            each group)
        number_format (ClickStackNumberFormat): The model property of type
            ClickStackNumberFormat.
        metric_data_type (MetricDataType): Metric data type, only for metrics data
            sources.
        metric_name (str): Metric name for metrics data sources
        display_type (DisplayType): Visual representation type for the time series
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "source_id": "sourceId",
        "agg_fn": "aggFn",
        "where": "where",
        "where_language": "whereLanguage",
        "group_by": "groupBy",
        "level": "level",
        "field": "field",
        "alias": "alias",
        "number_format": "numberFormat",
        "metric_data_type": "metricDataType",
        "metric_name": "metricName",
        "display_type": "displayType",
    }

    _optionals = [
        "level",
        "field",
        "alias",
        "number_format",
        "metric_data_type",
        "metric_name",
        "display_type",
    ]

    def __init__(
        self,
        source_id=None,
        agg_fn=None,
        where=None,
        where_language=None,
        group_by=None,
        level=APIHelper.SKIP,
        field=APIHelper.SKIP,
        alias=APIHelper.SKIP,
        number_format=APIHelper.SKIP,
        metric_data_type=APIHelper.SKIP,
        metric_name=APIHelper.SKIP,
        display_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackTimeChartSeries instance."""
        # Initialize members of the class
        self.mtype = "time"
        self.source_id = source_id
        self.agg_fn = agg_fn
        if level is not APIHelper.SKIP:
            self.level = level
        if field is not APIHelper.SKIP:
            self.field = field
        if alias is not APIHelper.SKIP:
            self.alias = alias
        self.where = where
        self.where_language = where_language
        self.group_by = group_by
        if number_format is not APIHelper.SKIP:
            self.number_format = number_format
        if metric_data_type is not APIHelper.SKIP:
            self.metric_data_type = metric_data_type
        if metric_name is not APIHelper.SKIP:
            self.metric_name = metric_name
        if display_type is not APIHelper.SKIP:
            self.display_type = display_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        source_id =\
            dictionary.get("sourceId")\
            if dictionary.get("sourceId")\
                else None
        agg_fn =\
            dictionary.get("aggFn")\
            if dictionary.get("aggFn")\
                else None
        where =\
            dictionary.get("where")\
            if dictionary.get("where")\
                else None
        where_language =\
            dictionary.get("whereLanguage")\
            if dictionary.get("whereLanguage")\
                else None
        group_by =\
            dictionary.get("groupBy")\
            if dictionary.get("groupBy")\
                else None
        level =\
            dictionary.get("level")\
            if dictionary.get("level")\
                else APIHelper.SKIP
        field =\
            dictionary.get("field")\
            if dictionary.get("field")\
                else APIHelper.SKIP
        alias =\
            dictionary.get("alias")\
            if dictionary.get("alias")\
                else APIHelper.SKIP
        number_format =\
            ClickStackNumberFormat.from_dictionary(
                dictionary.get("numberFormat"))\
                if "numberFormat" in dictionary.keys()\
                else APIHelper.SKIP
        metric_data_type =\
            dictionary.get("metricDataType")\
            if dictionary.get("metricDataType")\
                else APIHelper.SKIP
        metric_name =\
            dictionary.get("metricName")\
            if dictionary.get("metricName")\
                else APIHelper.SKIP
        display_type =\
            dictionary.get("displayType")\
            if dictionary.get("displayType")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(source_id,
                   agg_fn,
                   where,
                   where_language,
                   group_by,
                   level,
                   field,
                   alias,
                   number_format,
                   metric_data_type,
                   metric_name,
                   display_type,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.source_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.agg_fn,
                    type_callable=lambda value:
                        AggFn.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.where,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.where_language,
                    type_callable=lambda value:
                        WhereLanguage.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.group_by,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("sourceId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("aggFn"),
                type_callable=lambda value:
                    AggFn.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("where"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("whereLanguage"),
                type_callable=lambda value:
                    WhereLanguage.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("groupBy"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _source_id=self.source_id
        _agg_fn=self.agg_fn
        _level=(
            self.level
            if hasattr(self, "level")
            else None
        )
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _alias=(
            self.alias
            if hasattr(self, "alias")
            else None
        )
        _where=self.where
        _where_language=self.where_language
        _group_by=self.group_by
        _number_format=(
            self.number_format
            if hasattr(self, "number_format")
            else None
        )
        _metric_data_type=(
            self.metric_data_type
            if hasattr(self, "metric_data_type")
            else None
        )
        _metric_name=(
            self.metric_name
            if hasattr(self, "metric_name")
            else None
        )
        _display_type=(
            self.display_type
            if hasattr(self, "display_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"source_id={_source_id!r}, "
            f"agg_fn={_agg_fn!r}, "
            f"level={_level!r}, "
            f"field={_field!r}, "
            f"alias={_alias!r}, "
            f"where={_where!r}, "
            f"where_language={_where_language!r}, "
            f"group_by={_group_by!r}, "
            f"number_format={_number_format!r}, "
            f"metric_data_type={_metric_data_type!r}, "
            f"metric_name={_metric_name!r}, "
            f"display_type={_display_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _source_id=self.source_id
        _agg_fn=self.agg_fn
        _level=(
            self.level
            if hasattr(self, "level")
            else None
        )
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _alias=(
            self.alias
            if hasattr(self, "alias")
            else None
        )
        _where=self.where
        _where_language=self.where_language
        _group_by=self.group_by
        _number_format=(
            self.number_format
            if hasattr(self, "number_format")
            else None
        )
        _metric_data_type=(
            self.metric_data_type
            if hasattr(self, "metric_data_type")
            else None
        )
        _metric_name=(
            self.metric_name
            if hasattr(self, "metric_name")
            else None
        )
        _display_type=(
            self.display_type
            if hasattr(self, "display_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"source_id={_source_id!s}, "
            f"agg_fn={_agg_fn!s}, "
            f"level={_level!s}, "
            f"field={_field!s}, "
            f"alias={_alias!s}, "
            f"where={_where!s}, "
            f"where_language={_where_language!s}, "
            f"group_by={_group_by!s}, "
            f"number_format={_number_format!s}, "
            f"metric_data_type={_metric_data_type!s}, "
            f"metric_name={_metric_name!s}, "
            f"display_type={_display_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
