"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickPipePostgresPipeSettings(object):
    """Implementation of the 'ClickPipePostgresPipeSettings' model.

    Attributes:
        sync_interval_seconds (int): Interval in seconds to sync data from Postgres
            during CDC replication.
        pull_batch_size (int): Number of rows to pull in each batch during CDC
            replication.
        publication_name (str): PostgreSQL publication name to use for CDC
            replication. If not provided, ClickPipes will create one automatically.
        replication_mode (ReplicationMode): Replication mode: "cdc" (change data
            capture with initial snapshot), "snapshot" (one-time snapshot only), or
            "cdc_only" (CDC without initial snapshot).
        replication_slot_name (str): PostgreSQL replication slot name. Only valid for
            "cdc_only" mode. For "cdc" mode, ClickPipes creates the slot
            automatically.
        allow_nullable_columns (bool): Preserve nullability from Postgres in the
            destination ClickHouse table. When true, columns without NOT NULL
            constraints are created as Nullable(...). When false, all columns are
            non-nullable and NULL values are replaced with the default value for the
            type. Note: Nullable types have performance overhead in ClickHouse.
        initial_load_parallelism (int): Number of parallel workers to use per table
            in the initial snapshot phase.
        snapshot_num_rows_per_partition (int): Number of rows per partition during
            the snapshot phase.
        snapshot_number_of_parallel_tables (int): Number of tables to snapshot in
            parallel during the initial load phase.
        enable_failover_slots (bool): Enable failover support for the replication
            slot on PG17 and newer. Only applicable when ClickPipes creates the
            replication slot (i.e., replicationSlotName is NOT provided).
        delete_on_merge (bool): Enable hard delete behavior in ReplacingMergeTree for
            PostgreSQL DELETE operations.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sync_interval_seconds": "syncIntervalSeconds",
        "pull_batch_size": "pullBatchSize",
        "publication_name": "publicationName",
        "replication_mode": "replicationMode",
        "replication_slot_name": "replicationSlotName",
        "allow_nullable_columns": "allowNullableColumns",
        "initial_load_parallelism": "initialLoadParallelism",
        "snapshot_num_rows_per_partition": "snapshotNumRowsPerPartition",
        "snapshot_number_of_parallel_tables": "snapshotNumberOfParallelTables",
        "enable_failover_slots": "enableFailoverSlots",
        "delete_on_merge": "deleteOnMerge",
    }

    _optionals = [
        "sync_interval_seconds",
        "pull_batch_size",
        "publication_name",
        "replication_mode",
        "replication_slot_name",
        "allow_nullable_columns",
        "initial_load_parallelism",
        "snapshot_num_rows_per_partition",
        "snapshot_number_of_parallel_tables",
        "enable_failover_slots",
        "delete_on_merge",
    ]

    def __init__(
        self,
        sync_interval_seconds=APIHelper.SKIP,
        pull_batch_size=APIHelper.SKIP,
        publication_name=APIHelper.SKIP,
        replication_mode=APIHelper.SKIP,
        replication_slot_name=APIHelper.SKIP,
        allow_nullable_columns=APIHelper.SKIP,
        initial_load_parallelism=APIHelper.SKIP,
        snapshot_num_rows_per_partition=APIHelper.SKIP,
        snapshot_number_of_parallel_tables=APIHelper.SKIP,
        enable_failover_slots=APIHelper.SKIP,
        delete_on_merge=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipePostgresPipeSettings instance."""
        # Initialize members of the class
        if sync_interval_seconds is not APIHelper.SKIP:
            self.sync_interval_seconds = sync_interval_seconds
        if pull_batch_size is not APIHelper.SKIP:
            self.pull_batch_size = pull_batch_size
        if publication_name is not APIHelper.SKIP:
            self.publication_name = publication_name
        if replication_mode is not APIHelper.SKIP:
            self.replication_mode = replication_mode
        if replication_slot_name is not APIHelper.SKIP:
            self.replication_slot_name = replication_slot_name
        if allow_nullable_columns is not APIHelper.SKIP:
            self.allow_nullable_columns = allow_nullable_columns
        if initial_load_parallelism is not APIHelper.SKIP:
            self.initial_load_parallelism = initial_load_parallelism
        if snapshot_num_rows_per_partition is not APIHelper.SKIP:
            self.snapshot_num_rows_per_partition = snapshot_num_rows_per_partition
        if snapshot_number_of_parallel_tables is not APIHelper.SKIP:
            self.snapshot_number_of_parallel_tables =\
                 snapshot_number_of_parallel_tables
        if enable_failover_slots is not APIHelper.SKIP:
            self.enable_failover_slots = enable_failover_slots
        if delete_on_merge is not APIHelper.SKIP:
            self.delete_on_merge = delete_on_merge

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sync_interval_seconds =\
            dictionary.get("syncIntervalSeconds")\
            if dictionary.get("syncIntervalSeconds")\
                else APIHelper.SKIP
        pull_batch_size =\
            dictionary.get("pullBatchSize")\
            if dictionary.get("pullBatchSize")\
                else APIHelper.SKIP
        publication_name =\
            dictionary.get("publicationName")\
            if dictionary.get("publicationName")\
                else APIHelper.SKIP
        replication_mode =\
            dictionary.get("replicationMode")\
            if dictionary.get("replicationMode")\
                else APIHelper.SKIP
        replication_slot_name =\
            dictionary.get("replicationSlotName")\
            if dictionary.get("replicationSlotName")\
                else APIHelper.SKIP
        allow_nullable_columns =\
            dictionary.get("allowNullableColumns")\
            if "allowNullableColumns" in dictionary.keys()\
                else APIHelper.SKIP
        initial_load_parallelism =\
            dictionary.get("initialLoadParallelism")\
            if dictionary.get("initialLoadParallelism")\
                else APIHelper.SKIP
        snapshot_num_rows_per_partition =\
            dictionary.get("snapshotNumRowsPerPartition")\
            if dictionary.get("snapshotNumRowsPerPartition")\
                else APIHelper.SKIP
        snapshot_number_of_parallel_tables =\
            dictionary.get("snapshotNumberOfParallelTables")\
            if dictionary.get("snapshotNumberOfParallelTables")\
                else APIHelper.SKIP
        enable_failover_slots =\
            dictionary.get("enableFailoverSlots")\
            if "enableFailoverSlots" in dictionary.keys()\
                else APIHelper.SKIP
        delete_on_merge =\
            dictionary.get("deleteOnMerge")\
            if "deleteOnMerge" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(sync_interval_seconds,
                   pull_batch_size,
                   publication_name,
                   replication_mode,
                   replication_slot_name,
                   allow_nullable_columns,
                   initial_load_parallelism,
                   snapshot_num_rows_per_partition,
                   snapshot_number_of_parallel_tables,
                   enable_failover_slots,
                   delete_on_merge,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sync_interval_seconds=(
            self.sync_interval_seconds
            if hasattr(self, "sync_interval_seconds")
            else None
        )
        _pull_batch_size=(
            self.pull_batch_size
            if hasattr(self, "pull_batch_size")
            else None
        )
        _publication_name=(
            self.publication_name
            if hasattr(self, "publication_name")
            else None
        )
        _replication_mode=(
            self.replication_mode
            if hasattr(self, "replication_mode")
            else None
        )
        _replication_slot_name=(
            self.replication_slot_name
            if hasattr(self, "replication_slot_name")
            else None
        )
        _allow_nullable_columns=(
            self.allow_nullable_columns
            if hasattr(self, "allow_nullable_columns")
            else None
        )
        _initial_load_parallelism=(
            self.initial_load_parallelism
            if hasattr(self, "initial_load_parallelism")
            else None
        )
        _snapshot_num_rows_per_partition=(
            self.snapshot_num_rows_per_partition
            if hasattr(self, "snapshot_num_rows_per_partition")
            else None
        )
        _snapshot_number_of_parallel_tables=(
            self.snapshot_number_of_parallel_tables
            if hasattr(self, "snapshot_number_of_parallel_tables")
            else None
        )
        _enable_failover_slots=(
            self.enable_failover_slots
            if hasattr(self, "enable_failover_slots")
            else None
        )
        _delete_on_merge=(
            self.delete_on_merge
            if hasattr(self, "delete_on_merge")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sync_interval_seconds={_sync_interval_seconds!r}, "
            f"pull_batch_size={_pull_batch_size!r}, "
            f"publication_name={_publication_name!r}, "
            f"replication_mode={_replication_mode!r}, "
            f"replication_slot_name={_replication_slot_name!r}, "
            f"allow_nullable_columns={_allow_nullable_columns!r}, "
            f"initial_load_parallelism={_initial_load_parallelism!r}, "
            f"snapshot_num_rows_per_partition={_snapshot_num_rows_per_partition!r}, "
            f"snapshot_number_of_parallel_tables={_snapshot_number_of_parallel_tables!r}, "
            f"enable_failover_slots={_enable_failover_slots!r}, "
            f"delete_on_merge={_delete_on_merge!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sync_interval_seconds=(
            self.sync_interval_seconds
            if hasattr(self, "sync_interval_seconds")
            else None
        )
        _pull_batch_size=(
            self.pull_batch_size
            if hasattr(self, "pull_batch_size")
            else None
        )
        _publication_name=(
            self.publication_name
            if hasattr(self, "publication_name")
            else None
        )
        _replication_mode=(
            self.replication_mode
            if hasattr(self, "replication_mode")
            else None
        )
        _replication_slot_name=(
            self.replication_slot_name
            if hasattr(self, "replication_slot_name")
            else None
        )
        _allow_nullable_columns=(
            self.allow_nullable_columns
            if hasattr(self, "allow_nullable_columns")
            else None
        )
        _initial_load_parallelism=(
            self.initial_load_parallelism
            if hasattr(self, "initial_load_parallelism")
            else None
        )
        _snapshot_num_rows_per_partition=(
            self.snapshot_num_rows_per_partition
            if hasattr(self, "snapshot_num_rows_per_partition")
            else None
        )
        _snapshot_number_of_parallel_tables=(
            self.snapshot_number_of_parallel_tables
            if hasattr(self, "snapshot_number_of_parallel_tables")
            else None
        )
        _enable_failover_slots=(
            self.enable_failover_slots
            if hasattr(self, "enable_failover_slots")
            else None
        )
        _delete_on_merge=(
            self.delete_on_merge
            if hasattr(self, "delete_on_merge")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"sync_interval_seconds={_sync_interval_seconds!s}, "
            f"pull_batch_size={_pull_batch_size!s}, "
            f"publication_name={_publication_name!s}, "
            f"replication_mode={_replication_mode!s}, "
            f"replication_slot_name={_replication_slot_name!s}, "
            f"allow_nullable_columns={_allow_nullable_columns!s}, "
            f"initial_load_parallelism={_initial_load_parallelism!s}, "
            f"snapshot_num_rows_per_partition={_snapshot_num_rows_per_partition!s}, "
            f"snapshot_number_of_parallel_tables={_snapshot_number_of_parallel_tables!s}, "
            f"enable_failover_slots={_enable_failover_slots!s}, "
            f"delete_on_merge={_delete_on_merge!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
