"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickStackAlertSilenced(object):
    """Implementation of the 'ClickStackAlertSilenced' model.

    Attributes:
        by (str): User ID who silenced the alert.
        at (datetime): Silence start timestamp.
        until (datetime): Silence end timestamp.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "by": "by",
        "at": "at",
        "until": "until",
    }

    _optionals = [
        "by",
        "at",
        "until",
    ]

    _nullables = [
        "by",
    ]

    def __init__(
        self,
        by=APIHelper.SKIP,
        at=APIHelper.SKIP,
        until=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackAlertSilenced instance."""
        # Initialize members of the class
        if by is not APIHelper.SKIP:
            self.by = by
        if at is not APIHelper.SKIP:
            self.at =\
                 APIHelper.apply_datetime_converter(
                at, APIHelper.RFC3339DateTime)\
                 if at else None
        if until is not APIHelper.SKIP:
            self.until =\
                 APIHelper.apply_datetime_converter(
                until, APIHelper.RFC3339DateTime)\
                 if until else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        by =\
            dictionary.get("by")\
            if "by" in dictionary.keys()\
                else APIHelper.SKIP
        at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("at")).datetime\
            if dictionary.get("at") else APIHelper.SKIP
        until = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("until")).datetime\
            if dictionary.get("until") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(by,
                   at,
                   until,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _by=(
            self.by
            if hasattr(self, "by")
            else None
        )
        _at=(
            self.at
            if hasattr(self, "at")
            else None
        )
        _until=(
            self.until
            if hasattr(self, "until")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"by={_by!r}, "
            f"at={_at!r}, "
            f"until={_until!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _by=(
            self.by
            if hasattr(self, "by")
            else None
        )
        _at=(
            self.at
            if hasattr(self, "at")
            else None
        )
        _until=(
            self.until
            if hasattr(self, "until")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"by={_by!s}, "
            f"at={_at!s}, "
            f"until={_until!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
