"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_pipe_kafka_schema_registry_credentials import (  # noqa: E501
    ClickPipeKafkaSchemaRegistryCredentials,
)


class ClickPipeMutateKafkaSchemaRegistry(object):
    """Implementation of the 'ClickPipeMutateKafkaSchemaRegistry' model.

    Attributes:
        url (str): Schema URL. HTTPS required.
        authentication (Authentication): Authentication type of the schema registry.
        ca_certificate (str): PEM encoded CA certificates to validate the schema
            registry's certificate.
        credentials (ClickPipeKafkaSchemaRegistryCredentials): The model property of
            type ClickPipeKafkaSchemaRegistryCredentials.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "authentication": "authentication",
        "ca_certificate": "caCertificate",
        "credentials": "credentials",
    }

    _optionals = [
        "url",
        "authentication",
        "ca_certificate",
        "credentials",
    ]

    _nullables = [
        "ca_certificate",
    ]

    def __init__(
        self,
        url=APIHelper.SKIP,
        authentication=APIHelper.SKIP,
        ca_certificate=APIHelper.SKIP,
        credentials=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipeMutateKafkaSchemaRegistry instance."""
        # Initialize members of the class
        if url is not APIHelper.SKIP:
            self.url = url
        if authentication is not APIHelper.SKIP:
            self.authentication = authentication
        if ca_certificate is not APIHelper.SKIP:
            self.ca_certificate = ca_certificate
        if credentials is not APIHelper.SKIP:
            self.credentials = credentials

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        authentication =\
            dictionary.get("authentication")\
            if dictionary.get("authentication")\
                else APIHelper.SKIP
        ca_certificate =\
            dictionary.get("caCertificate")\
            if "caCertificate" in dictionary.keys()\
                else APIHelper.SKIP
        credentials =\
            ClickPipeKafkaSchemaRegistryCredentials.from_dictionary(
                dictionary.get("credentials"))\
                if "credentials" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   authentication,
                   ca_certificate,
                   credentials,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _authentication=(
            self.authentication
            if hasattr(self, "authentication")
            else None
        )
        _ca_certificate=(
            self.ca_certificate
            if hasattr(self, "ca_certificate")
            else None
        )
        _credentials=(
            self.credentials
            if hasattr(self, "credentials")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!r}, "
            f"authentication={_authentication!r}, "
            f"ca_certificate={_ca_certificate!r}, "
            f"credentials={_credentials!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _authentication=(
            self.authentication
            if hasattr(self, "authentication")
            else None
        )
        _ca_certificate=(
            self.ca_certificate
            if hasattr(self, "ca_certificate")
            else None
        )
        _credentials=(
            self.credentials
            if hasattr(self, "credentials")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!s}, "
            f"authentication={_authentication!s}, "
            f"ca_certificate={_ca_certificate!s}, "
            f"credentials={_credentials!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
