"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.color_1 import (
    Color1,
)
from openapispecforclickhousecloud.models.operator_1 import (
    Operator1,
)


class ClickStackEqualityColorCondition(object):
    """Implementation of the 'ClickStackEqualityColorCondition' model.

    Attributes:
        operator (Operator1): Equality comparison operator.
        value (float | str): A finite number, or a string up to 200 characters, to
            compare for equality.
        color (Color1): Color applied when the rule matches.
        label (str): Optional label describing the rule.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "operator": "operator",
        "value": "value",
        "color": "color",
        "label": "label",
    }

    _optionals = [
        "label",
    ]

    def __init__(
        self,
        operator=None,
        value=None,
        color=None,
        label=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackEqualityColorCondition instance."""
        # Initialize members of the class
        self.operator = operator
        self.value = value
        self.color = color
        if label is not APIHelper.SKIP:
            self.label = label

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from openapispecforclickhousecloud.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        operator =\
            dictionary.get("operator")\
            if dictionary.get("operator")\
                else None
        value = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("ClickStackEqualityColorConditionValue"),
            dictionary.get("value"),
            False)\
            if dictionary.get("value") is not None\
            else None
        color =\
            dictionary.get("color")\
            if dictionary.get("color")\
                else None
        label =\
            dictionary.get("label")\
            if dictionary.get("label")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(operator,
                   value,
                   color,
                   label,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from openapispecforclickhousecloud.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.operator,
                    type_callable=lambda value:
                        Operator1.validate(value)) \
                and (UnionTypeLookUp.get("ClickStackEqualityColorConditionValue")
                .validate(dictionary.value).is_valid) \
                and APIHelper.is_valid_type(
                    value=dictionary.color,
                    type_callable=lambda value:
                        Color1.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("operator"),
                type_callable=lambda value:
                    Operator1.validate(value)) \
            and (UnionTypeLookUp.get("ClickStackEqualityColorConditionValue")
            .validate(dictionary.get("value")).is_valid) \
            and APIHelper.is_valid_type(
                value=dictionary.get("color"),
                type_callable=lambda value:
                    Color1.validate(value))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _operator=self.operator
        _value=self.value
        _color=self.color
        _label=(
            self.label
            if hasattr(self, "label")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"operator={_operator!r}, "
            f"value={_value!r}, "
            f"color={_color!r}, "
            f"label={_label!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _operator=self.operator
        _value=self.value
        _color=self.color
        _label=(
            self.label
            if hasattr(self, "label")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"operator={_operator!s}, "
            f"value={_value!s}, "
            f"color={_color!s}, "
            f"label={_label!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
