"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.msk_iam_user import (
    MskIamUser,
)


class ClickPipePostKinesisSource(object):
    """Implementation of the 'ClickPipePostKinesisSource' model.

    Attributes:
        format (Format2): Format of the Kinesis stream.
        stream_name (str): Name of the Kinesis stream.
        region (str): AWS region of the Kinesis stream.
        use_enhanced_fan_out (bool): Use enhanced fan-out for the Kinesis stream.
        iterator_type (IteratorType): Type of iterator to use when reading from the
            Kinesis stream. If AT_TIMESTAMP is used, the timestamp field must be
            provided.
        timestamp (int): UNIX timestamp to start reading from the Kinesis stream.
            Required if iteratorType is AT_TIMESTAMP.
        authentication (Authentication5): Authentication method to use with the
            Kinesis stream.
        iam_role (str): IAM role to use for authentication. Required if IAM_ROLE is
            used.
        access_key (MskIamUser): The model property of type MskIamUser.
        protobuf_schema (str): Base64-encoded .proto source or serialized
            FileDescriptorSet. Required with Protobuf format and not supported with
            other formats.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "format": "format",
        "stream_name": "streamName",
        "region": "region",
        "use_enhanced_fan_out": "useEnhancedFanOut",
        "iterator_type": "iteratorType",
        "timestamp": "timestamp",
        "authentication": "authentication",
        "iam_role": "iamRole",
        "access_key": "accessKey",
        "protobuf_schema": "protobufSchema",
    }

    _optionals = [
        "format",
        "stream_name",
        "region",
        "use_enhanced_fan_out",
        "iterator_type",
        "timestamp",
        "authentication",
        "iam_role",
        "access_key",
        "protobuf_schema",
    ]

    _nullables = [
        "use_enhanced_fan_out",
        "timestamp",
        "iam_role",
        "access_key",
    ]

    def __init__(
        self,
        format=APIHelper.SKIP,
        stream_name=APIHelper.SKIP,
        region=APIHelper.SKIP,
        use_enhanced_fan_out=APIHelper.SKIP,
        iterator_type=APIHelper.SKIP,
        timestamp=APIHelper.SKIP,
        authentication=APIHelper.SKIP,
        iam_role=APIHelper.SKIP,
        access_key=APIHelper.SKIP,
        protobuf_schema=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipePostKinesisSource instance."""
        # Initialize members of the class
        if format is not APIHelper.SKIP:
            self.format = format
        if stream_name is not APIHelper.SKIP:
            self.stream_name = stream_name
        if region is not APIHelper.SKIP:
            self.region = region
        if use_enhanced_fan_out is not APIHelper.SKIP:
            self.use_enhanced_fan_out = use_enhanced_fan_out
        if iterator_type is not APIHelper.SKIP:
            self.iterator_type = iterator_type
        if timestamp is not APIHelper.SKIP:
            self.timestamp = timestamp
        if authentication is not APIHelper.SKIP:
            self.authentication = authentication
        if iam_role is not APIHelper.SKIP:
            self.iam_role = iam_role
        if access_key is not APIHelper.SKIP:
            self.access_key = access_key
        if protobuf_schema is not APIHelper.SKIP:
            self.protobuf_schema = protobuf_schema

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        format =\
            dictionary.get("format")\
            if dictionary.get("format")\
                else APIHelper.SKIP
        stream_name =\
            dictionary.get("streamName")\
            if dictionary.get("streamName")\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else APIHelper.SKIP
        use_enhanced_fan_out =\
            dictionary.get("useEnhancedFanOut")\
            if "useEnhancedFanOut" in dictionary.keys()\
                else APIHelper.SKIP
        iterator_type =\
            dictionary.get("iteratorType")\
            if dictionary.get("iteratorType")\
                else APIHelper.SKIP
        timestamp =\
            dictionary.get("timestamp")\
            if "timestamp" in dictionary.keys()\
                else APIHelper.SKIP
        authentication =\
            dictionary.get("authentication")\
            if dictionary.get("authentication")\
                else APIHelper.SKIP
        iam_role =\
            dictionary.get("iamRole")\
            if "iamRole" in dictionary.keys()\
                else APIHelper.SKIP
        if "accessKey" in dictionary.keys():
            access_key =\
                MskIamUser.from_dictionary(
                dictionary.get("accessKey"))\
                if dictionary.get("accessKey") else None
        else:
            access_key = APIHelper.SKIP
        protobuf_schema =\
            dictionary.get("protobufSchema")\
            if dictionary.get("protobufSchema")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(format,
                   stream_name,
                   region,
                   use_enhanced_fan_out,
                   iterator_type,
                   timestamp,
                   authentication,
                   iam_role,
                   access_key,
                   protobuf_schema,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _format=(
            self.format
            if hasattr(self, "format")
            else None
        )
        _stream_name=(
            self.stream_name
            if hasattr(self, "stream_name")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _use_enhanced_fan_out=(
            self.use_enhanced_fan_out
            if hasattr(self, "use_enhanced_fan_out")
            else None
        )
        _iterator_type=(
            self.iterator_type
            if hasattr(self, "iterator_type")
            else None
        )
        _timestamp=(
            self.timestamp
            if hasattr(self, "timestamp")
            else None
        )
        _authentication=(
            self.authentication
            if hasattr(self, "authentication")
            else None
        )
        _iam_role=(
            self.iam_role
            if hasattr(self, "iam_role")
            else None
        )
        _access_key=(
            self.access_key
            if hasattr(self, "access_key")
            else None
        )
        _protobuf_schema=(
            self.protobuf_schema
            if hasattr(self, "protobuf_schema")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"format={_format!r}, "
            f"stream_name={_stream_name!r}, "
            f"region={_region!r}, "
            f"use_enhanced_fan_out={_use_enhanced_fan_out!r}, "
            f"iterator_type={_iterator_type!r}, "
            f"timestamp={_timestamp!r}, "
            f"authentication={_authentication!r}, "
            f"iam_role={_iam_role!r}, "
            f"access_key={_access_key!r}, "
            f"protobuf_schema={_protobuf_schema!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _format=(
            self.format
            if hasattr(self, "format")
            else None
        )
        _stream_name=(
            self.stream_name
            if hasattr(self, "stream_name")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _use_enhanced_fan_out=(
            self.use_enhanced_fan_out
            if hasattr(self, "use_enhanced_fan_out")
            else None
        )
        _iterator_type=(
            self.iterator_type
            if hasattr(self, "iterator_type")
            else None
        )
        _timestamp=(
            self.timestamp
            if hasattr(self, "timestamp")
            else None
        )
        _authentication=(
            self.authentication
            if hasattr(self, "authentication")
            else None
        )
        _iam_role=(
            self.iam_role
            if hasattr(self, "iam_role")
            else None
        )
        _access_key=(
            self.access_key
            if hasattr(self, "access_key")
            else None
        )
        _protobuf_schema=(
            self.protobuf_schema
            if hasattr(self, "protobuf_schema")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"format={_format!s}, "
            f"stream_name={_stream_name!s}, "
            f"region={_region!s}, "
            f"use_enhanced_fan_out={_use_enhanced_fan_out!s}, "
            f"iterator_type={_iterator_type!s}, "
            f"timestamp={_timestamp!s}, "
            f"authentication={_authentication!s}, "
            f"iam_role={_iam_role!s}, "
            f"access_key={_access_key!s}, "
            f"protobuf_schema={_protobuf_schema!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
