"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_stack_formula import (
    ClickStackFormula,
)
from openapispecforclickhousecloud.models.click_stack_number_format import (
    ClickStackNumberFormat,
)
from openapispecforclickhousecloud.models.click_stack_select_item import (
    ClickStackSelectItem,
)


class ClickStackLineBuilderChartConfig(object):
    """Implementation of the 'ClickStackLineBuilderChartConfig' model.

    Attributes:
        display_type (str): Display type discriminator. Must be "line" for line
            charts.
        source_id (str): ID of the data source to query.
        select (List[ClickStackSelectItem]): One or more aggregated values to plot.
            When asRatio is true, exactly two select items are required.
        group_by (str): Field expression to group results by (creates separate lines
            per group value).
        as_ratio (bool): Plot select[0] / select[1] as a ratio. Requires exactly two
            select items.
        align_date_range_to_granularity (bool): Expand date range boundaries to the
            query granularity interval.
        fill_nulls (bool): Fill missing time buckets with zero instead of leaving
            gaps.
        fit_y_axis_to_data (bool): Set the y-axis lower bound to the minimum of the
            displayed data instead of zero, making small fluctuations between series
            easier to see.
        number_format (ClickStackNumberFormat): The model property of type
            ClickStackNumberFormat.
        compare_to_previous_period (bool): Overlay the equivalent previous time
            period for comparison.
        series_limit (int): Maximum number of series rendered (top-N by value). Omit
            to use the default render cap, set 0 for unlimited, or a positive N to
            keep the top N series.
        formulas (List[ClickStackFormula]): Derived series computed from the select
            items via letter-ref arithmetic ("A" = select[0], "B" = select[1], ...).
            Metric, log, and trace sources only. Cannot be combined with asRatio.
        show_operand_series (bool): Only meaningful with formulas. When false, only
            the formula series are returned; the raw operand series are hidden.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "display_type": "displayType",
        "source_id": "sourceId",
        "select": "select",
        "group_by": "groupBy",
        "as_ratio": "asRatio",
        "align_date_range_to_granularity": "alignDateRangeToGranularity",
        "fill_nulls": "fillNulls",
        "fit_y_axis_to_data": "fitYAxisToData",
        "number_format": "numberFormat",
        "compare_to_previous_period": "compareToPreviousPeriod",
        "series_limit": "seriesLimit",
        "formulas": "formulas",
        "show_operand_series": "showOperandSeries",
    }

    _optionals = [
        "group_by",
        "as_ratio",
        "align_date_range_to_granularity",
        "fill_nulls",
        "fit_y_axis_to_data",
        "number_format",
        "compare_to_previous_period",
        "series_limit",
        "formulas",
        "show_operand_series",
    ]

    def __init__(
        self,
        source_id=None,
        select=None,
        group_by=APIHelper.SKIP,
        as_ratio=APIHelper.SKIP,
        align_date_range_to_granularity=APIHelper.SKIP,
        fill_nulls=APIHelper.SKIP,
        fit_y_axis_to_data=APIHelper.SKIP,
        number_format=APIHelper.SKIP,
        compare_to_previous_period=APIHelper.SKIP,
        series_limit=APIHelper.SKIP,
        formulas=APIHelper.SKIP,
        show_operand_series=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackLineBuilderChartConfig instance."""
        # Initialize members of the class
        self.display_type = "line"
        self.source_id = source_id
        self.select = select
        if group_by is not APIHelper.SKIP:
            self.group_by = group_by
        if as_ratio is not APIHelper.SKIP:
            self.as_ratio = as_ratio
        if align_date_range_to_granularity is not APIHelper.SKIP:
            self.align_date_range_to_granularity = align_date_range_to_granularity
        if fill_nulls is not APIHelper.SKIP:
            self.fill_nulls = fill_nulls
        if fit_y_axis_to_data is not APIHelper.SKIP:
            self.fit_y_axis_to_data = fit_y_axis_to_data
        if number_format is not APIHelper.SKIP:
            self.number_format = number_format
        if compare_to_previous_period is not APIHelper.SKIP:
            self.compare_to_previous_period = compare_to_previous_period
        if series_limit is not APIHelper.SKIP:
            self.series_limit = series_limit
        if formulas is not APIHelper.SKIP:
            self.formulas = formulas
        if show_operand_series is not APIHelper.SKIP:
            self.show_operand_series = show_operand_series

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        source_id =\
            dictionary.get("sourceId")\
            if dictionary.get("sourceId")\
                else None
        select = None
        if dictionary.get("select") is not None:
            select = [
                ClickStackSelectItem.from_dictionary(x)
                    for x in dictionary.get("select")
            ]
        group_by =\
            dictionary.get("groupBy")\
            if dictionary.get("groupBy")\
                else APIHelper.SKIP
        as_ratio =\
            dictionary.get("asRatio")\
            if "asRatio" in dictionary.keys()\
                else APIHelper.SKIP
        align_date_range_to_granularity =\
            dictionary.get("alignDateRangeToGranularity")\
            if "alignDateRangeToGranularity" in dictionary.keys()\
                else APIHelper.SKIP
        fill_nulls =\
            dictionary.get("fillNulls")\
            if "fillNulls" in dictionary.keys()\
                else APIHelper.SKIP
        fit_y_axis_to_data =\
            dictionary.get("fitYAxisToData")\
            if "fitYAxisToData" in dictionary.keys()\
                else APIHelper.SKIP
        number_format =\
            ClickStackNumberFormat.from_dictionary(
                dictionary.get("numberFormat"))\
                if "numberFormat" in dictionary.keys()\
                else APIHelper.SKIP
        compare_to_previous_period =\
            dictionary.get("compareToPreviousPeriod")\
            if "compareToPreviousPeriod" in dictionary.keys()\
                else APIHelper.SKIP
        series_limit =\
            dictionary.get("seriesLimit")\
            if dictionary.get("seriesLimit")\
                else APIHelper.SKIP
        formulas = None
        if dictionary.get("formulas") is not None:
            formulas = [
                ClickStackFormula.from_dictionary(x)
                    for x in dictionary.get("formulas")
            ]
        else:
            formulas = APIHelper.SKIP
        show_operand_series =\
            dictionary.get("showOperandSeries")\
            if "showOperandSeries" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(source_id,
                   select,
                   group_by,
                   as_ratio,
                   align_date_range_to_granularity,
                   fill_nulls,
                   fit_y_axis_to_data,
                   number_format,
                   compare_to_previous_period,
                   series_limit,
                   formulas,
                   show_operand_series,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.display_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.source_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.select,
                    type_callable=lambda value:
                        ClickStackSelectItem.validate(value),
                    is_model_dict=True,
                    is_inner_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("displayType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("sourceId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("select"),
                type_callable=lambda value:
                    ClickStackSelectItem.validate(value),
                is_model_dict=True,
                is_inner_model_dict=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _display_type=self.display_type
        _source_id=self.source_id
        _select=self.select
        _group_by=(
            self.group_by
            if hasattr(self, "group_by")
            else None
        )
        _as_ratio=(
            self.as_ratio
            if hasattr(self, "as_ratio")
            else None
        )
        _align_date_range_to_granularity=(
            self.align_date_range_to_granularity
            if hasattr(self, "align_date_range_to_granularity")
            else None
        )
        _fill_nulls=(
            self.fill_nulls
            if hasattr(self, "fill_nulls")
            else None
        )
        _fit_y_axis_to_data=(
            self.fit_y_axis_to_data
            if hasattr(self, "fit_y_axis_to_data")
            else None
        )
        _number_format=(
            self.number_format
            if hasattr(self, "number_format")
            else None
        )
        _compare_to_previous_period=(
            self.compare_to_previous_period
            if hasattr(self, "compare_to_previous_period")
            else None
        )
        _series_limit=(
            self.series_limit
            if hasattr(self, "series_limit")
            else None
        )
        _formulas=(
            self.formulas
            if hasattr(self, "formulas")
            else None
        )
        _show_operand_series=(
            self.show_operand_series
            if hasattr(self, "show_operand_series")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"display_type={_display_type!r}, "
            f"source_id={_source_id!r}, "
            f"select={_select!r}, "
            f"group_by={_group_by!r}, "
            f"as_ratio={_as_ratio!r}, "
            f"align_date_range_to_granularity={_align_date_range_to_granularity!r}, "
            f"fill_nulls={_fill_nulls!r}, "
            f"fit_y_axis_to_data={_fit_y_axis_to_data!r}, "
            f"number_format={_number_format!r}, "
            f"compare_to_previous_period={_compare_to_previous_period!r}, "
            f"series_limit={_series_limit!r}, "
            f"formulas={_formulas!r}, "
            f"show_operand_series={_show_operand_series!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _display_type=self.display_type
        _source_id=self.source_id
        _select=self.select
        _group_by=(
            self.group_by
            if hasattr(self, "group_by")
            else None
        )
        _as_ratio=(
            self.as_ratio
            if hasattr(self, "as_ratio")
            else None
        )
        _align_date_range_to_granularity=(
            self.align_date_range_to_granularity
            if hasattr(self, "align_date_range_to_granularity")
            else None
        )
        _fill_nulls=(
            self.fill_nulls
            if hasattr(self, "fill_nulls")
            else None
        )
        _fit_y_axis_to_data=(
            self.fit_y_axis_to_data
            if hasattr(self, "fit_y_axis_to_data")
            else None
        )
        _number_format=(
            self.number_format
            if hasattr(self, "number_format")
            else None
        )
        _compare_to_previous_period=(
            self.compare_to_previous_period
            if hasattr(self, "compare_to_previous_period")
            else None
        )
        _series_limit=(
            self.series_limit
            if hasattr(self, "series_limit")
            else None
        )
        _formulas=(
            self.formulas
            if hasattr(self, "formulas")
            else None
        )
        _show_operand_series=(
            self.show_operand_series
            if hasattr(self, "show_operand_series")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"display_type={_display_type!s}, "
            f"source_id={_source_id!s}, "
            f"select={_select!s}, "
            f"group_by={_group_by!s}, "
            f"as_ratio={_as_ratio!s}, "
            f"align_date_range_to_granularity={_align_date_range_to_granularity!s}, "
            f"fill_nulls={_fill_nulls!s}, "
            f"fit_y_axis_to_data={_fit_y_axis_to_data!s}, "
            f"number_format={_number_format!s}, "
            f"compare_to_previous_period={_compare_to_previous_period!s}, "
            f"series_limit={_series_limit!s}, "
            f"formulas={_formulas!s}, "
            f"show_operand_series={_show_operand_series!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
