"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickStackLogSourceMetadataMaterializedViews(object):
    """Implementation of the 'ClickStackLogSourceMetadataMaterializedViews' model.

    Attributes:
        key_rollup_table (str): ClickHouse table name for the key rollup (field
            discovery).
        kv_rollup_table (str): ClickHouse table name for the key-value rollup (value
            autocomplete).
        granularity (str): The time granularity of the rollup tables.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key_rollup_table": "keyRollupTable",
        "kv_rollup_table": "kvRollupTable",
        "granularity": "granularity",
    }

    _optionals = [
        "key_rollup_table",
        "kv_rollup_table",
        "granularity",
    ]

    def __init__(
        self,
        key_rollup_table=APIHelper.SKIP,
        kv_rollup_table=APIHelper.SKIP,
        granularity=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackLogSourceMetadataMaterializedViews instance."""
        # Initialize members of the class
        if key_rollup_table is not APIHelper.SKIP:
            self.key_rollup_table = key_rollup_table
        if kv_rollup_table is not APIHelper.SKIP:
            self.kv_rollup_table = kv_rollup_table
        if granularity is not APIHelper.SKIP:
            self.granularity = granularity

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        key_rollup_table =\
            dictionary.get("keyRollupTable")\
            if dictionary.get("keyRollupTable")\
                else APIHelper.SKIP
        kv_rollup_table =\
            dictionary.get("kvRollupTable")\
            if dictionary.get("kvRollupTable")\
                else APIHelper.SKIP
        granularity =\
            dictionary.get("granularity")\
            if dictionary.get("granularity")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(key_rollup_table,
                   kv_rollup_table,
                   granularity,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _key_rollup_table=(
            self.key_rollup_table
            if hasattr(self, "key_rollup_table")
            else None
        )
        _kv_rollup_table=(
            self.kv_rollup_table
            if hasattr(self, "kv_rollup_table")
            else None
        )
        _granularity=(
            self.granularity
            if hasattr(self, "granularity")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key_rollup_table={_key_rollup_table!r}, "
            f"kv_rollup_table={_kv_rollup_table!r}, "
            f"granularity={_granularity!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _key_rollup_table=(
            self.key_rollup_table
            if hasattr(self, "key_rollup_table")
            else None
        )
        _kv_rollup_table=(
            self.kv_rollup_table
            if hasattr(self, "kv_rollup_table")
            else None
        )
        _granularity=(
            self.granularity
            if hasattr(self, "granularity")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key_rollup_table={_key_rollup_table!s}, "
            f"kv_rollup_table={_kv_rollup_table!s}, "
            f"granularity={_granularity!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
