"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_stack_number_format import (
    ClickStackNumberFormat,
)


class ClickStackPieRawSqlChartConfig(object):
    """Implementation of the 'ClickStackPieRawSqlChartConfig' model.

    Attributes:
        config_type (str): Must be "sql" to use the Raw SQL chart config variant.
        connection_id (str): ID of the ClickHouse connection to execute the query
            against.
        sql_template (str): SQL query template to execute. Supports HyperDX template
            variables.
        source_id (str): Optional ID of the data source associated with this Raw SQL
            chart. Used for applying dashboard filters.
        number_format (ClickStackNumberFormat): The model property of type
            ClickStackNumberFormat.
        display_type (str): Display as a pie chart.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "config_type": "configType",
        "connection_id": "connectionId",
        "sql_template": "sqlTemplate",
        "display_type": "displayType",
        "source_id": "sourceId",
        "number_format": "numberFormat",
    }

    _optionals = [
        "source_id",
        "number_format",
    ]

    def __init__(
        self,
        connection_id=None,
        sql_template=None,
        source_id=APIHelper.SKIP,
        number_format=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackPieRawSqlChartConfig instance."""
        # Initialize members of the class
        self.config_type = "sql"
        self.connection_id = connection_id
        self.sql_template = sql_template
        if source_id is not APIHelper.SKIP:
            self.source_id = source_id
        if number_format is not APIHelper.SKIP:
            self.number_format = number_format
        self.display_type = "pie"

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        connection_id =\
            dictionary.get("connectionId")\
            if dictionary.get("connectionId")\
                else None
        sql_template =\
            dictionary.get("sqlTemplate")\
            if dictionary.get("sqlTemplate")\
                else None
        source_id =\
            dictionary.get("sourceId")\
            if dictionary.get("sourceId")\
                else APIHelper.SKIP
        number_format =\
            ClickStackNumberFormat.from_dictionary(
                dictionary.get("numberFormat"))\
                if "numberFormat" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(connection_id,
                   sql_template,
                   source_id,
                   number_format,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.config_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.connection_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.sql_template,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.display_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("configType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("connectionId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("sqlTemplate"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("displayType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _config_type=self.config_type
        _connection_id=self.connection_id
        _sql_template=self.sql_template
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _number_format=(
            self.number_format
            if hasattr(self, "number_format")
            else None
        )
        _display_type=self.display_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"config_type={_config_type!r}, "
            f"connection_id={_connection_id!r}, "
            f"sql_template={_sql_template!r}, "
            f"source_id={_source_id!r}, "
            f"number_format={_number_format!r}, "
            f"display_type={_display_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _config_type=self.config_type
        _connection_id=self.connection_id
        _sql_template=self.sql_template
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _number_format=(
            self.number_format
            if hasattr(self, "number_format")
            else None
        )
        _display_type=self.display_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"config_type={_config_type!s}, "
            f"connection_id={_connection_id!s}, "
            f"sql_template={_sql_template!s}, "
            f"source_id={_source_id!s}, "
            f"number_format={_number_format!s}, "
            f"display_type={_display_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
