"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_stack_dashboard_container import (
    ClickStackDashboardContainer,
)
from openapispecforclickhousecloud.models.click_stack_filter import (
    ClickStackFilter,
)
from openapispecforclickhousecloud.models.click_stack_tile_output import (
    ClickStackTileOutput,
)


class ClickStackDashboardResponse(object):
    """Implementation of the 'ClickStackDashboardResponse' model.

    Attributes:
        id (str): Dashboard ID
        name (str): Dashboard name
        tiles (List[ClickStackTileOutput]): List of tiles/charts in the dashboard
        tags (List[str]): Tags for organizing and filtering dashboards
        filters (List[ClickStackFilter]): Dropdown filters added to the dashboard.
            Each one broadcasts its selected value as a condition, acts as a variable
            which can be referenced in tile queries, or both.
        saved_query (str): Optional default dashboard query restored when loading the
            dashboard.
        saved_query_language (SavedQueryLanguage): Query language used by savedQuery.
        saved_filter_values (List[ClickStackSqlSavedFilterValue |
            ClickStackVariableSavedFilterValue] | None): Optional default dashboard
            filter values restored when loading the dashboard.
        containers (List[ClickStackDashboardContainer]): Optional grouping
            containers. Each tile may join a container via tile.containerId, and a
            tab inside it via tile.tabId.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "tiles": "tiles",
        "tags": "tags",
        "filters": "filters",
        "saved_query": "savedQuery",
        "saved_query_language": "savedQueryLanguage",
        "saved_filter_values": "savedFilterValues",
        "containers": "containers",
    }

    _optionals = [
        "id",
        "name",
        "tiles",
        "tags",
        "filters",
        "saved_query",
        "saved_query_language",
        "saved_filter_values",
        "containers",
    ]

    _nullables = [
        "saved_query",
        "saved_query_language",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        tiles=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        filters=APIHelper.SKIP,
        saved_query=APIHelper.SKIP,
        saved_query_language=APIHelper.SKIP,
        saved_filter_values=APIHelper.SKIP,
        containers=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackDashboardResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if tiles is not APIHelper.SKIP:
            self.tiles = tiles
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if filters is not APIHelper.SKIP:
            self.filters = filters
        if saved_query is not APIHelper.SKIP:
            self.saved_query = saved_query
        if saved_query_language is not APIHelper.SKIP:
            self.saved_query_language = saved_query_language
        if saved_filter_values is not APIHelper.SKIP:
            self.saved_filter_values = saved_filter_values
        if containers is not APIHelper.SKIP:
            self.containers = containers

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from openapispecforclickhousecloud.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        tiles = None
        if dictionary.get("tiles") is not None:
            tiles = [
                ClickStackTileOutput.from_dictionary(x)
                    for x in dictionary.get("tiles")
            ]
        else:
            tiles = APIHelper.SKIP
        tags =\
            dictionary.get("tags")\
            if dictionary.get("tags")\
                else APIHelper.SKIP
        filters = None
        if dictionary.get("filters") is not None:
            filters = [
                ClickStackFilter.from_dictionary(x)
                    for x in dictionary.get("filters")
            ]
        else:
            filters = APIHelper.SKIP
        saved_query =\
            dictionary.get("savedQuery")\
            if "savedQuery" in dictionary.keys()\
                else APIHelper.SKIP
        saved_query_language =\
            dictionary.get("savedQueryLanguage")\
            if "savedQueryLanguage" in dictionary.keys()\
                else APIHelper.SKIP
        saved_filter_values = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("ClickStackSavedFilterValue"),
            dictionary.get("savedFilterValues"),
            False)\
            if dictionary.get("savedFilterValues") is not None\
            else APIHelper.SKIP
        containers = None
        if dictionary.get("containers") is not None:
            containers = [
                ClickStackDashboardContainer.from_dictionary(x)
                    for x in dictionary.get("containers")
            ]
        else:
            containers = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   name,
                   tiles,
                   tags,
                   filters,
                   saved_query,
                   saved_query_language,
                   saved_filter_values,
                   containers,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _tiles=(
            self.tiles
            if hasattr(self, "tiles")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _filters=(
            self.filters
            if hasattr(self, "filters")
            else None
        )
        _saved_query=(
            self.saved_query
            if hasattr(self, "saved_query")
            else None
        )
        _saved_query_language=(
            self.saved_query_language
            if hasattr(self, "saved_query_language")
            else None
        )
        _saved_filter_values=(
            self.saved_filter_values
            if hasattr(self, "saved_filter_values")
            else None
        )
        _containers=(
            self.containers
            if hasattr(self, "containers")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"tiles={_tiles!r}, "
            f"tags={_tags!r}, "
            f"filters={_filters!r}, "
            f"saved_query={_saved_query!r}, "
            f"saved_query_language={_saved_query_language!r}, "
            f"saved_filter_values={_saved_filter_values!r}, "
            f"containers={_containers!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _tiles=(
            self.tiles
            if hasattr(self, "tiles")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _filters=(
            self.filters
            if hasattr(self, "filters")
            else None
        )
        _saved_query=(
            self.saved_query
            if hasattr(self, "saved_query")
            else None
        )
        _saved_query_language=(
            self.saved_query_language
            if hasattr(self, "saved_query_language")
            else None
        )
        _saved_filter_values=(
            self.saved_filter_values
            if hasattr(self, "saved_filter_values")
            else None
        )
        _containers=(
            self.containers
            if hasattr(self, "containers")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"tiles={_tiles!s}, "
            f"tags={_tags!s}, "
            f"filters={_filters!s}, "
            f"saved_query={_saved_query!s}, "
            f"saved_query_language={_saved_query_language!s}, "
            f"saved_filter_values={_saved_filter_values!s}, "
            f"containers={_containers!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
