"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_pipe_mongo_db_pipe_settings import (
    ClickPipeMongoDbPipeSettings,
)
from openapispecforclickhousecloud.models.click_pipe_mongo_db_pipe_table_mapping import (  # noqa: E501
    ClickPipeMongoDbPipeTableMapping,
)


class ClickPipeMongoDbSource(object):
    """Implementation of the 'ClickPipeMongoDBSource' model.

    Attributes:
        uri (str): MongoDB connection URI. Supports both standard URIs
            (mongodb://...) and SRV URIs (mongodb+srv://...). Embedded credentials
            are redacted from API responses, so the returned value can differ from
            what was submitted.
        read_preference (ReadPreference): MongoDB read preference for replica set
            reads.
        tls_host (str): TLS/SSL host for secure connections.
        disable_tls (bool): Disable TLS for the MongoDB connection. Defaults to false
            (TLS enabled).
        skip_cert_verification (bool): Skip TLS certificate verification for the
            MongoDB connection. Use with caution in production environments.
        ca_certificate (str): PEM encoded CA certificate to validate the MongoDB
            server certificate.
        settings (ClickPipeMongoDbPipeSettings): The model property of type
            ClickPipeMongoDbPipeSettings.
        table_mappings (List[ClickPipeMongoDbPipeTableMapping]): List of collection
            mappings defining which MongoDB collections to replicate and how they map
            to ClickHouse tables.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uri": "uri",
        "read_preference": "readPreference",
        "tls_host": "tlsHost",
        "disable_tls": "disableTls",
        "skip_cert_verification": "skipCertVerification",
        "ca_certificate": "caCertificate",
        "settings": "settings",
        "table_mappings": "tableMappings",
    }

    _optionals = [
        "tls_host",
        "disable_tls",
        "skip_cert_verification",
        "ca_certificate",
        "settings",
        "table_mappings",
    ]

    def __init__(
        self,
        uri=None,
        read_preference=None,
        tls_host=APIHelper.SKIP,
        disable_tls=APIHelper.SKIP,
        skip_cert_verification=APIHelper.SKIP,
        ca_certificate=APIHelper.SKIP,
        settings=APIHelper.SKIP,
        table_mappings=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipeMongoDbSource instance."""
        # Initialize members of the class
        self.uri = uri
        self.read_preference = read_preference
        if tls_host is not APIHelper.SKIP:
            self.tls_host = tls_host
        if disable_tls is not APIHelper.SKIP:
            self.disable_tls = disable_tls
        if skip_cert_verification is not APIHelper.SKIP:
            self.skip_cert_verification = skip_cert_verification
        if ca_certificate is not APIHelper.SKIP:
            self.ca_certificate = ca_certificate
        if settings is not APIHelper.SKIP:
            self.settings = settings
        if table_mappings is not APIHelper.SKIP:
            self.table_mappings = table_mappings

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        uri =\
            dictionary.get("uri")\
            if dictionary.get("uri")\
                else None
        read_preference =\
            dictionary.get("readPreference")\
            if dictionary.get("readPreference")\
                else None
        tls_host =\
            dictionary.get("tlsHost")\
            if dictionary.get("tlsHost")\
                else APIHelper.SKIP
        disable_tls =\
            dictionary.get("disableTls")\
            if "disableTls" in dictionary.keys()\
                else APIHelper.SKIP
        skip_cert_verification =\
            dictionary.get("skipCertVerification")\
            if "skipCertVerification" in dictionary.keys()\
                else APIHelper.SKIP
        ca_certificate =\
            dictionary.get("caCertificate")\
            if dictionary.get("caCertificate")\
                else APIHelper.SKIP
        settings =\
            ClickPipeMongoDbPipeSettings.from_dictionary(
                dictionary.get("settings"))\
                if "settings" in dictionary.keys()\
                else APIHelper.SKIP
        table_mappings = None
        if dictionary.get("tableMappings") is not None:
            table_mappings = [
                ClickPipeMongoDbPipeTableMapping.from_dictionary(x)
                    for x in dictionary.get("tableMappings")
            ]
        else:
            table_mappings = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(uri,
                   read_preference,
                   tls_host,
                   disable_tls,
                   skip_cert_verification,
                   ca_certificate,
                   settings,
                   table_mappings,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _uri=self.uri
        _read_preference=self.read_preference
        _tls_host=(
            self.tls_host
            if hasattr(self, "tls_host")
            else None
        )
        _disable_tls=(
            self.disable_tls
            if hasattr(self, "disable_tls")
            else None
        )
        _skip_cert_verification=(
            self.skip_cert_verification
            if hasattr(self, "skip_cert_verification")
            else None
        )
        _ca_certificate=(
            self.ca_certificate
            if hasattr(self, "ca_certificate")
            else None
        )
        _settings=(
            self.settings
            if hasattr(self, "settings")
            else None
        )
        _table_mappings=(
            self.table_mappings
            if hasattr(self, "table_mappings")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"uri={_uri!r}, "
            f"read_preference={_read_preference!r}, "
            f"tls_host={_tls_host!r}, "
            f"disable_tls={_disable_tls!r}, "
            f"skip_cert_verification={_skip_cert_verification!r}, "
            f"ca_certificate={_ca_certificate!r}, "
            f"settings={_settings!r}, "
            f"table_mappings={_table_mappings!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _uri=self.uri
        _read_preference=self.read_preference
        _tls_host=(
            self.tls_host
            if hasattr(self, "tls_host")
            else None
        )
        _disable_tls=(
            self.disable_tls
            if hasattr(self, "disable_tls")
            else None
        )
        _skip_cert_verification=(
            self.skip_cert_verification
            if hasattr(self, "skip_cert_verification")
            else None
        )
        _ca_certificate=(
            self.ca_certificate
            if hasattr(self, "ca_certificate")
            else None
        )
        _settings=(
            self.settings
            if hasattr(self, "settings")
            else None
        )
        _table_mappings=(
            self.table_mappings
            if hasattr(self, "table_mappings")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"uri={_uri!s}, "
            f"read_preference={_read_preference!s}, "
            f"tls_host={_tls_host!s}, "
            f"disable_tls={_disable_tls!s}, "
            f"skip_cert_verification={_skip_cert_verification!s}, "
            f"ca_certificate={_ca_certificate!s}, "
            f"settings={_settings!s}, "
            f"table_mappings={_table_mappings!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
