"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.click_pipe_patch_postgres_pipe_remove_table_mapping import (  # noqa: E501
    ClickPipePatchPostgresPipeRemoveTableMapping,
)
from openapispecforclickhousecloud.models.click_pipe_patch_postgres_pipe_settings import (  # noqa: E501
    ClickPipePatchPostgresPipeSettings,
)
from openapispecforclickhousecloud.models.click_pipe_postgres_pipe_table_mapping import (  # noqa: E501
    ClickPipePostgresPipeTableMapping,
)
from openapispecforclickhousecloud.models.plain import (
    Plain,
)


class ClickPipePatchPostgresSource(object):
    """Implementation of the 'ClickPipePatchPostgresSource' model.

    Attributes:
        credentials (Plain): The model property of type Plain.
        host (str): PostgreSQL server hostname or IP address. To use a reverse
            private endpoint, pass the endpoint hostname here.
        port (int): PostgreSQL server port.
        database (str): PostgreSQL database name to replicate from.
        tls_host (str): TLS/SSL host for secure connections.
        ca_certificate (str): PEM encoded CA certificate to validate the Postgres
            server certificate.
        disable_tls (bool): Disable TLS for the Postgres connection. Use with caution
            in production environments.
        skip_cert_verification (bool): Skip TLS certificate verification for the
            Postgres connection. Use with caution in production environments.
        settings (ClickPipePatchPostgresPipeSettings): The model property of type
            ClickPipePatchPostgresPipeSettings.
        table_mappings_to_add (List[ClickPipePostgresPipeTableMapping]): Table
            mappings to add to the pipe. Can be an empty array if no tables are being
            added.
        table_mappings_to_remove
            (List[ClickPipePatchPostgresPipeRemoveTableMapping]): Table mappings to
            remove from the pipe. Only sourceSchemaName, sourceTable, and targetTable
            are required for removal.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "credentials": "credentials",
        "host": "host",
        "port": "port",
        "database": "database",
        "tls_host": "tlsHost",
        "ca_certificate": "caCertificate",
        "disable_tls": "disableTls",
        "skip_cert_verification": "skipCertVerification",
        "settings": "settings",
        "table_mappings_to_add": "tableMappingsToAdd",
        "table_mappings_to_remove": "tableMappingsToRemove",
    }

    _optionals = [
        "credentials",
        "host",
        "port",
        "database",
        "tls_host",
        "ca_certificate",
        "disable_tls",
        "skip_cert_verification",
        "settings",
        "table_mappings_to_add",
        "table_mappings_to_remove",
    ]

    _nullables = [
        "host",
        "port",
        "database",
        "tls_host",
        "ca_certificate",
        "disable_tls",
        "skip_cert_verification",
    ]

    def __init__(
        self,
        credentials=APIHelper.SKIP,
        host=APIHelper.SKIP,
        port=APIHelper.SKIP,
        database=APIHelper.SKIP,
        tls_host=APIHelper.SKIP,
        ca_certificate=APIHelper.SKIP,
        disable_tls=APIHelper.SKIP,
        skip_cert_verification=APIHelper.SKIP,
        settings=APIHelper.SKIP,
        table_mappings_to_add=APIHelper.SKIP,
        table_mappings_to_remove=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickPipePatchPostgresSource instance."""
        # Initialize members of the class
        if credentials is not APIHelper.SKIP:
            self.credentials = credentials
        if host is not APIHelper.SKIP:
            self.host = host
        if port is not APIHelper.SKIP:
            self.port = port
        if database is not APIHelper.SKIP:
            self.database = database
        if tls_host is not APIHelper.SKIP:
            self.tls_host = tls_host
        if ca_certificate is not APIHelper.SKIP:
            self.ca_certificate = ca_certificate
        if disable_tls is not APIHelper.SKIP:
            self.disable_tls = disable_tls
        if skip_cert_verification is not APIHelper.SKIP:
            self.skip_cert_verification = skip_cert_verification
        if settings is not APIHelper.SKIP:
            self.settings = settings
        if table_mappings_to_add is not APIHelper.SKIP:
            self.table_mappings_to_add = table_mappings_to_add
        if table_mappings_to_remove is not APIHelper.SKIP:
            self.table_mappings_to_remove = table_mappings_to_remove

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        credentials =\
            Plain.from_dictionary(
                dictionary.get("credentials"))\
                if "credentials" in dictionary.keys()\
                else APIHelper.SKIP
        host =\
            dictionary.get("host")\
            if "host" in dictionary.keys()\
                else APIHelper.SKIP
        port =\
            dictionary.get("port")\
            if "port" in dictionary.keys()\
                else APIHelper.SKIP
        database =\
            dictionary.get("database")\
            if "database" in dictionary.keys()\
                else APIHelper.SKIP
        tls_host =\
            dictionary.get("tlsHost")\
            if "tlsHost" in dictionary.keys()\
                else APIHelper.SKIP
        ca_certificate =\
            dictionary.get("caCertificate")\
            if "caCertificate" in dictionary.keys()\
                else APIHelper.SKIP
        disable_tls =\
            dictionary.get("disableTls")\
            if "disableTls" in dictionary.keys()\
                else APIHelper.SKIP
        skip_cert_verification =\
            dictionary.get("skipCertVerification")\
            if "skipCertVerification" in dictionary.keys()\
                else APIHelper.SKIP
        settings =\
            ClickPipePatchPostgresPipeSettings.from_dictionary(
                dictionary.get("settings"))\
                if "settings" in dictionary.keys()\
                else APIHelper.SKIP
        table_mappings_to_add = None
        if dictionary.get("tableMappingsToAdd") is not None:
            table_mappings_to_add = [
                ClickPipePostgresPipeTableMapping.from_dictionary(x)
                    for x in dictionary.get("tableMappingsToAdd")
            ]
        else:
            table_mappings_to_add = APIHelper.SKIP
        table_mappings_to_remove = None
        if dictionary.get("tableMappingsToRemove") is not None:
            table_mappings_to_remove = [
                ClickPipePatchPostgresPipeRemoveTableMapping.from_dictionary(x)
                    for x in dictionary.get("tableMappingsToRemove")
            ]
        else:
            table_mappings_to_remove = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(credentials,
                   host,
                   port,
                   database,
                   tls_host,
                   ca_certificate,
                   disable_tls,
                   skip_cert_verification,
                   settings,
                   table_mappings_to_add,
                   table_mappings_to_remove,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _credentials=(
            self.credentials
            if hasattr(self, "credentials")
            else None
        )
        _host=(
            self.host
            if hasattr(self, "host")
            else None
        )
        _port=(
            self.port
            if hasattr(self, "port")
            else None
        )
        _database=(
            self.database
            if hasattr(self, "database")
            else None
        )
        _tls_host=(
            self.tls_host
            if hasattr(self, "tls_host")
            else None
        )
        _ca_certificate=(
            self.ca_certificate
            if hasattr(self, "ca_certificate")
            else None
        )
        _disable_tls=(
            self.disable_tls
            if hasattr(self, "disable_tls")
            else None
        )
        _skip_cert_verification=(
            self.skip_cert_verification
            if hasattr(self, "skip_cert_verification")
            else None
        )
        _settings=(
            self.settings
            if hasattr(self, "settings")
            else None
        )
        _table_mappings_to_add=(
            self.table_mappings_to_add
            if hasattr(self, "table_mappings_to_add")
            else None
        )
        _table_mappings_to_remove=(
            self.table_mappings_to_remove
            if hasattr(self, "table_mappings_to_remove")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"credentials={_credentials!r}, "
            f"host={_host!r}, "
            f"port={_port!r}, "
            f"database={_database!r}, "
            f"tls_host={_tls_host!r}, "
            f"ca_certificate={_ca_certificate!r}, "
            f"disable_tls={_disable_tls!r}, "
            f"skip_cert_verification={_skip_cert_verification!r}, "
            f"settings={_settings!r}, "
            f"table_mappings_to_add={_table_mappings_to_add!r}, "
            f"table_mappings_to_remove={_table_mappings_to_remove!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _credentials=(
            self.credentials
            if hasattr(self, "credentials")
            else None
        )
        _host=(
            self.host
            if hasattr(self, "host")
            else None
        )
        _port=(
            self.port
            if hasattr(self, "port")
            else None
        )
        _database=(
            self.database
            if hasattr(self, "database")
            else None
        )
        _tls_host=(
            self.tls_host
            if hasattr(self, "tls_host")
            else None
        )
        _ca_certificate=(
            self.ca_certificate
            if hasattr(self, "ca_certificate")
            else None
        )
        _disable_tls=(
            self.disable_tls
            if hasattr(self, "disable_tls")
            else None
        )
        _skip_cert_verification=(
            self.skip_cert_verification
            if hasattr(self, "skip_cert_verification")
            else None
        )
        _settings=(
            self.settings
            if hasattr(self, "settings")
            else None
        )
        _table_mappings_to_add=(
            self.table_mappings_to_add
            if hasattr(self, "table_mappings_to_add")
            else None
        )
        _table_mappings_to_remove=(
            self.table_mappings_to_remove
            if hasattr(self, "table_mappings_to_remove")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"credentials={_credentials!s}, "
            f"host={_host!s}, "
            f"port={_port!s}, "
            f"database={_database!s}, "
            f"tls_host={_tls_host!s}, "
            f"ca_certificate={_ca_certificate!s}, "
            f"disable_tls={_disable_tls!s}, "
            f"skip_cert_verification={_skip_cert_verification!s}, "
            f"settings={_settings!s}, "
            f"table_mappings_to_add={_table_mappings_to_add!s}, "
            f"table_mappings_to_remove={_table_mappings_to_remove!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
