"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ClickStackSlackWebhook(object):
    """Implementation of the 'ClickStackSlackWebhook' model.

    Attributes:
        id (str): Webhook ID
        name (str): Webhook name
        service (str): Webhook service type
        url (str): Slack incoming webhook URL
        description (str): Webhook description, shown in the UI
        updated_at (datetime): Last update timestamp
        created_at (datetime): Creation timestamp
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "service": "service",
        "updated_at": "updatedAt",
        "created_at": "createdAt",
        "url": "url",
        "description": "description",
    }

    _optionals = [
        "url",
        "description",
    ]

    def __init__(
        self,
        id=None,
        name=None,
        updated_at=None,
        created_at=None,
        url=APIHelper.SKIP,
        description=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ClickStackSlackWebhook instance."""
        # Initialize members of the class
        self.id = id
        self.name = name
        self.service = "slack"
        if url is not APIHelper.SKIP:
            self.url = url
        if description is not APIHelper.SKIP:
            self.description = description
        self.updated_at =\
             APIHelper.apply_datetime_converter(
            updated_at, APIHelper.RFC3339DateTime)\
             if updated_at else None
        self.created_at =\
             APIHelper.apply_datetime_converter(
            created_at, APIHelper.RFC3339DateTime)\
             if created_at else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updatedAt")).datetime\
            if dictionary.get("updatedAt") else None
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("createdAt")).datetime\
            if dictionary.get("createdAt") else None
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   name,
                   updated_at,
                   created_at,
                   url,
                   description,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.service,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.updated_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.created_at,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        APIHelper.RFC3339DateTime,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("id"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("name"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("service"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("updatedAt"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("createdAt"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _name=self.name
        _service=self.service
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _updated_at=self.updated_at
        _created_at=self.created_at
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"service={_service!r}, "
            f"url={_url!r}, "
            f"description={_description!r}, "
            f"updated_at={_updated_at!r}, "
            f"created_at={_created_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _name=self.name
        _service=self.service
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _updated_at=self.updated_at
        _created_at=self.created_at
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"service={_service!s}, "
            f"url={_url!s}, "
            f"description={_description!s}, "
            f"updated_at={_updated_at!s}, "
            f"created_at={_created_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
