"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Color1(object):
    """Implementation of the 'Color1' enum.

    Color applied when the rule matches.

    Attributes:
        CHARTBLUE: The enum member of type str.
        CHARTORANGE: The enum member of type str.
        CHARTRED: The enum member of type str.
        CHARTCYAN: The enum member of type str.
        CHARTGREEN: The enum member of type str.
        CHARTPINK: The enum member of type str.
        CHARTPURPLE: The enum member of type str.
        CHARTLIGHTBLUE: The enum member of type str.
        CHARTBROWN: The enum member of type str.
        CHARTGRAY: The enum member of type str.
        CHARTSUCCESS: The enum member of type str.
        CHARTWARNING: The enum member of type str.
        CHARTERROR: The enum member of type str.

    """

    _all_values = ["chart-blue", "chart-orange", "chart-red", "chart-cyan", "chart-green",
        "chart-pink", "chart-purple", "chart-light-blue", "chart-brown", "chart-gray",
        "chart-success", "chart-warning", "chart-error"]
    CHARTBLUE = "chart-blue"

    CHARTORANGE = "chart-orange"

    CHARTRED = "chart-red"

    CHARTCYAN = "chart-cyan"

    CHARTGREEN = "chart-green"

    CHARTPINK = "chart-pink"

    CHARTPURPLE = "chart-purple"

    CHARTLIGHTBLUE = "chart-light-blue"

    CHARTBROWN = "chart-brown"

    CHARTGRAY = "chart-gray"

    CHARTSUCCESS = "chart-success"

    CHARTWARNING = "chart-warning"

    CHARTERROR = "chart-error"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
