"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Command(object):
    """Implementation of the 'Command' enum.

    Postgres status, which initiates a process.

    Attributes:
        RESTART: The enum member of type str.
        PROMOTE: The enum member of type str.
        SWITCHOVER: The enum member of type str.

    """

    RESTART = "restart"

    PROMOTE = "promote"

    SWITCHOVER = "switchover"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
