"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class CurrentScaling(object):
    """Implementation of the 'CurrentScaling' model.

    Attributes:
        effective_autoscaling_mode (EffectiveAutoscalingMode): Autoscaling mode
            currently in effect on the running service. May diverge from the
            configured baseline mode while a schedule entry is active.
        effective_min_replica_memory_gb (float): Minimum memory per replica (Gb)
            currently applied to the running service. May diverge from the top-level
            `minReplicaMemoryGb` baseline while a schedule entry is active.
        effective_max_replica_memory_gb (float): Maximum memory per replica (Gb)
            currently applied to the running service. May diverge from the top-level
            `maxReplicaMemoryGb` baseline while a schedule entry is active. Reflects
            the stored value: normally equal to `effectiveMinReplicaMemoryGb` in
            horizontal mode, but a legacy service stored with an unequal memory range
            reports the stored bounds as-is.
        effective_min_replicas (int): Minimum number of replicas currently applied to
            the running service. May diverge from the baseline while a schedule entry
            is active. Reflects the stored value: normally equal to
            `effectiveMaxReplicas` in vertical mode (a fixed replica count), but a
            legacy service stored with an unequal replica range reports the stored
            bounds as-is.
        effective_max_replicas (int): Maximum number of replicas currently applied to
            the running service. May diverge from the baseline while a schedule entry
            is active.
        effective_idle_scaling (bool): Whether idle scaling is currently in effect on
            the service. May diverge from the top-level `idleScaling` baseline while
            a schedule entry is active.
        effective_idle_timeout_minutes (int): Idle timeout in minutes currently in
            effect on the service. May diverge from the top-level
            `idleTimeoutMinutes` baseline while a schedule entry is active.
        active_entry_id (uuid|str): ID of the schedule entry whose values are
            currently applied to the service. Absent when no entry is active.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "effective_autoscaling_mode": "effectiveAutoscalingMode",
        "effective_min_replica_memory_gb": "effectiveMinReplicaMemoryGb",
        "effective_max_replica_memory_gb": "effectiveMaxReplicaMemoryGb",
        "effective_min_replicas": "effectiveMinReplicas",
        "effective_max_replicas": "effectiveMaxReplicas",
        "effective_idle_scaling": "effectiveIdleScaling",
        "effective_idle_timeout_minutes": "effectiveIdleTimeoutMinutes",
        "active_entry_id": "activeEntryId",
    }

    _optionals = [
        "effective_autoscaling_mode",
        "effective_min_replica_memory_gb",
        "effective_max_replica_memory_gb",
        "effective_min_replicas",
        "effective_max_replicas",
        "effective_idle_scaling",
        "effective_idle_timeout_minutes",
        "active_entry_id",
    ]

    def __init__(
        self,
        effective_autoscaling_mode=APIHelper.SKIP,
        effective_min_replica_memory_gb=APIHelper.SKIP,
        effective_max_replica_memory_gb=APIHelper.SKIP,
        effective_min_replicas=APIHelper.SKIP,
        effective_max_replicas=APIHelper.SKIP,
        effective_idle_scaling=APIHelper.SKIP,
        effective_idle_timeout_minutes=APIHelper.SKIP,
        active_entry_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CurrentScaling instance."""
        # Initialize members of the class
        if effective_autoscaling_mode is not APIHelper.SKIP:
            self.effective_autoscaling_mode = effective_autoscaling_mode
        if effective_min_replica_memory_gb is not APIHelper.SKIP:
            self.effective_min_replica_memory_gb = effective_min_replica_memory_gb
        if effective_max_replica_memory_gb is not APIHelper.SKIP:
            self.effective_max_replica_memory_gb = effective_max_replica_memory_gb
        if effective_min_replicas is not APIHelper.SKIP:
            self.effective_min_replicas = effective_min_replicas
        if effective_max_replicas is not APIHelper.SKIP:
            self.effective_max_replicas = effective_max_replicas
        if effective_idle_scaling is not APIHelper.SKIP:
            self.effective_idle_scaling = effective_idle_scaling
        if effective_idle_timeout_minutes is not APIHelper.SKIP:
            self.effective_idle_timeout_minutes = effective_idle_timeout_minutes
        if active_entry_id is not APIHelper.SKIP:
            self.active_entry_id = active_entry_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        effective_autoscaling_mode =\
            dictionary.get("effectiveAutoscalingMode")\
            if dictionary.get("effectiveAutoscalingMode")\
                else APIHelper.SKIP
        effective_min_replica_memory_gb =\
            dictionary.get("effectiveMinReplicaMemoryGb")\
            if dictionary.get("effectiveMinReplicaMemoryGb")\
                else APIHelper.SKIP
        effective_max_replica_memory_gb =\
            dictionary.get("effectiveMaxReplicaMemoryGb")\
            if dictionary.get("effectiveMaxReplicaMemoryGb")\
                else APIHelper.SKIP
        effective_min_replicas =\
            dictionary.get("effectiveMinReplicas")\
            if dictionary.get("effectiveMinReplicas")\
                else APIHelper.SKIP
        effective_max_replicas =\
            dictionary.get("effectiveMaxReplicas")\
            if dictionary.get("effectiveMaxReplicas")\
                else APIHelper.SKIP
        effective_idle_scaling =\
            dictionary.get("effectiveIdleScaling")\
            if "effectiveIdleScaling" in dictionary.keys()\
                else APIHelper.SKIP
        effective_idle_timeout_minutes =\
            dictionary.get("effectiveIdleTimeoutMinutes")\
            if dictionary.get("effectiveIdleTimeoutMinutes")\
                else APIHelper.SKIP
        active_entry_id =\
            dictionary.get("activeEntryId")\
            if dictionary.get("activeEntryId")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(effective_autoscaling_mode,
                   effective_min_replica_memory_gb,
                   effective_max_replica_memory_gb,
                   effective_min_replicas,
                   effective_max_replicas,
                   effective_idle_scaling,
                   effective_idle_timeout_minutes,
                   active_entry_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _effective_autoscaling_mode=(
            self.effective_autoscaling_mode
            if hasattr(self, "effective_autoscaling_mode")
            else None
        )
        _effective_min_replica_memory_gb=(
            self.effective_min_replica_memory_gb
            if hasattr(self, "effective_min_replica_memory_gb")
            else None
        )
        _effective_max_replica_memory_gb=(
            self.effective_max_replica_memory_gb
            if hasattr(self, "effective_max_replica_memory_gb")
            else None
        )
        _effective_min_replicas=(
            self.effective_min_replicas
            if hasattr(self, "effective_min_replicas")
            else None
        )
        _effective_max_replicas=(
            self.effective_max_replicas
            if hasattr(self, "effective_max_replicas")
            else None
        )
        _effective_idle_scaling=(
            self.effective_idle_scaling
            if hasattr(self, "effective_idle_scaling")
            else None
        )
        _effective_idle_timeout_minutes=(
            self.effective_idle_timeout_minutes
            if hasattr(self, "effective_idle_timeout_minutes")
            else None
        )
        _active_entry_id=(
            self.active_entry_id
            if hasattr(self, "active_entry_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"effective_autoscaling_mode={_effective_autoscaling_mode!r}, "
            f"effective_min_replica_memory_gb={_effective_min_replica_memory_gb!r}, "
            f"effective_max_replica_memory_gb={_effective_max_replica_memory_gb!r}, "
            f"effective_min_replicas={_effective_min_replicas!r}, "
            f"effective_max_replicas={_effective_max_replicas!r}, "
            f"effective_idle_scaling={_effective_idle_scaling!r}, "
            f"effective_idle_timeout_minutes={_effective_idle_timeout_minutes!r}, "
            f"active_entry_id={_active_entry_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _effective_autoscaling_mode=(
            self.effective_autoscaling_mode
            if hasattr(self, "effective_autoscaling_mode")
            else None
        )
        _effective_min_replica_memory_gb=(
            self.effective_min_replica_memory_gb
            if hasattr(self, "effective_min_replica_memory_gb")
            else None
        )
        _effective_max_replica_memory_gb=(
            self.effective_max_replica_memory_gb
            if hasattr(self, "effective_max_replica_memory_gb")
            else None
        )
        _effective_min_replicas=(
            self.effective_min_replicas
            if hasattr(self, "effective_min_replicas")
            else None
        )
        _effective_max_replicas=(
            self.effective_max_replicas
            if hasattr(self, "effective_max_replicas")
            else None
        )
        _effective_idle_scaling=(
            self.effective_idle_scaling
            if hasattr(self, "effective_idle_scaling")
            else None
        )
        _effective_idle_timeout_minutes=(
            self.effective_idle_timeout_minutes
            if hasattr(self, "effective_idle_timeout_minutes")
            else None
        )
        _active_entry_id=(
            self.active_entry_id
            if hasattr(self, "active_entry_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"effective_autoscaling_mode={_effective_autoscaling_mode!s}, "
            f"effective_min_replica_memory_gb={_effective_min_replica_memory_gb!s}, "
            f"effective_max_replica_memory_gb={_effective_max_replica_memory_gb!s}, "
            f"effective_min_replicas={_effective_min_replicas!s}, "
            f"effective_max_replicas={_effective_max_replicas!s}, "
            f"effective_idle_scaling={_effective_idle_scaling!s}, "
            f"effective_idle_timeout_minutes={_effective_idle_timeout_minutes!s}, "
            f"active_entry_id={_active_entry_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
