"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class GcpBackupBucketPostRequestV1(object):
    """Implementation of the 'GcpBackupBucketPostRequestV1' model.

    Attributes:
        bucket_provider (BucketProvider1): Bucket provider
        bucket_path (str): Bucket path
        access_key_id (str): Access Key ID (HMAC key)
        secret_access_key (str): Secret Access Key (HMAC secret key)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bucket_provider": "bucketProvider",
        "bucket_path": "bucketPath",
        "access_key_id": "accessKeyId",
        "secret_access_key": "secretAccessKey",
    }

    _optionals = [
        "bucket_provider",
        "bucket_path",
        "access_key_id",
        "secret_access_key",
    ]

    def __init__(
        self,
        bucket_provider=APIHelper.SKIP,
        bucket_path=APIHelper.SKIP,
        access_key_id=APIHelper.SKIP,
        secret_access_key=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GcpBackupBucketPostRequestV1 instance."""
        # Initialize members of the class
        if bucket_provider is not APIHelper.SKIP:
            self.bucket_provider = bucket_provider
        if bucket_path is not APIHelper.SKIP:
            self.bucket_path = bucket_path
        if access_key_id is not APIHelper.SKIP:
            self.access_key_id = access_key_id
        if secret_access_key is not APIHelper.SKIP:
            self.secret_access_key = secret_access_key

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        bucket_provider =\
            dictionary.get("bucketProvider")\
            if dictionary.get("bucketProvider")\
                else APIHelper.SKIP
        bucket_path =\
            dictionary.get("bucketPath")\
            if dictionary.get("bucketPath")\
                else APIHelper.SKIP
        access_key_id =\
            dictionary.get("accessKeyId")\
            if dictionary.get("accessKeyId")\
                else APIHelper.SKIP
        secret_access_key =\
            dictionary.get("secretAccessKey")\
            if dictionary.get("secretAccessKey")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(bucket_provider,
                   bucket_path,
                   access_key_id,
                   secret_access_key,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _bucket_provider=(
            self.bucket_provider
            if hasattr(self, "bucket_provider")
            else None
        )
        _bucket_path=(
            self.bucket_path
            if hasattr(self, "bucket_path")
            else None
        )
        _access_key_id=(
            self.access_key_id
            if hasattr(self, "access_key_id")
            else None
        )
        _secret_access_key=(
            self.secret_access_key
            if hasattr(self, "secret_access_key")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bucket_provider={_bucket_provider!r}, "
            f"bucket_path={_bucket_path!r}, "
            f"access_key_id={_access_key_id!r}, "
            f"secret_access_key={_secret_access_key!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _bucket_provider=(
            self.bucket_provider
            if hasattr(self, "bucket_provider")
            else None
        )
        _bucket_path=(
            self.bucket_path
            if hasattr(self, "bucket_path")
            else None
        )
        _access_key_id=(
            self.access_key_id
            if hasattr(self, "access_key_id")
            else None
        )
        _secret_access_key=(
            self.secret_access_key
            if hasattr(self, "secret_access_key")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bucket_provider={_bucket_provider!s}, "
            f"bucket_path={_bucket_path!s}, "
            f"access_key_id={_access_key_id!s}, "
            f"secret_access_key={_secret_access_key!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
