"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class OrganizationPatchPrivateEndpoint(object):
    """Implementation of the 'OrganizationPatchPrivateEndpoint' model.

    Attributes:
        id (str): Private endpoint identifier
        description (str): Optional description of private endpoint
        cloud_provider (CloudProvider1): Cloud provider in which the private endpoint
            is lcoated
        region (Region1): Region in which the private endpoint is located
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "description": "description",
        "cloud_provider": "cloudProvider",
        "region": "region",
    }

    _optionals = [
        "id",
        "description",
        "cloud_provider",
        "region",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        description=APIHelper.SKIP,
        cloud_provider=APIHelper.SKIP,
        region=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OrganizationPatchPrivateEndpoint instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if description is not APIHelper.SKIP:
            self.description = description
        if cloud_provider is not APIHelper.SKIP:
            self.cloud_provider = cloud_provider
        if region is not APIHelper.SKIP:
            self.region = region

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        cloud_provider =\
            dictionary.get("cloudProvider")\
            if dictionary.get("cloudProvider")\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   description,
                   cloud_provider,
                   region,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _cloud_provider=(
            self.cloud_provider
            if hasattr(self, "cloud_provider")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"description={_description!r}, "
            f"cloud_provider={_cloud_provider!r}, "
            f"region={_region!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _cloud_provider=(
            self.cloud_provider
            if hasattr(self, "cloud_provider")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"description={_description!s}, "
            f"cloud_provider={_cloud_provider!s}, "
            f"region={_region!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
