"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.postgres_configuration import (
    PostgresConfiguration,
)
from openapispecforclickhousecloud.models.resource_tags_v_1 import (
    ResourceTagsV1,
)


class PostgresServicePostRequest(object):
    """Implementation of the 'PostgresServicePostRequest' model.

    Attributes:
        name (str): Name of the Postgres service. Alphanumerical string with
            whitespaces up to 50 characters.
        provider (CloudProvider): The cloud provider for a Postgres service.
        region (str): The cloud region for a Postgres service.
        postgres_version (PostgresMajorVersion): The model property of type
            PostgresMajorVersion.
        size (VmSize): The VM size for a Postgres service.
        ha_type (PgHaType): Type of high availability: “none” for no replication,
            “async” for asynchronous replication to a single standby, and “sync” for
            synchronous replication to two standbys.
        tags (List[ResourceTagsV1]): Tags associated with the Postgres service. Tag
            keys starting with “chc_” are reserved for internal use.
        pg_config (PostgresConfiguration): Postgres [runtime
            configuration](https://www.postgresql.org/docs/current/runtime-config.html
            ) configuration.
        pg_bouncer_config (Dict[str, str]): PgBouncer [runtime
            configuration](https://www.pgbouncer.org/config.html) configuration.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "provider": "provider",
        "region": "region",
        "size": "size",
        "postgres_version": "postgresVersion",
        "ha_type": "haType",
        "tags": "tags",
        "pg_config": "pgConfig",
        "pg_bouncer_config": "pgBouncerConfig",
    }

    _optionals = [
        "postgres_version",
        "ha_type",
        "tags",
        "pg_config",
        "pg_bouncer_config",
    ]

    def __init__(
        self,
        name=None,
        provider=None,
        region=None,
        size=None,
        postgres_version=APIHelper.SKIP,
        ha_type=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        pg_config=APIHelper.SKIP,
        pg_bouncer_config=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PostgresServicePostRequest instance."""
        # Initialize members of the class
        self.name = name
        self.provider = provider
        self.region = region
        if postgres_version is not APIHelper.SKIP:
            self.postgres_version = postgres_version
        self.size = size
        if ha_type is not APIHelper.SKIP:
            self.ha_type = ha_type
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if pg_config is not APIHelper.SKIP:
            self.pg_config = pg_config
        if pg_bouncer_config is not APIHelper.SKIP:
            self.pg_bouncer_config = pg_bouncer_config

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        provider =\
            dictionary.get("provider")\
            if dictionary.get("provider")\
                else None
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else None
        size =\
            dictionary.get("size")\
            if dictionary.get("size")\
                else None
        postgres_version =\
            dictionary.get("postgresVersion")\
            if dictionary.get("postgresVersion")\
                else APIHelper.SKIP
        ha_type =\
            dictionary.get("haType")\
            if dictionary.get("haType")\
                else APIHelper.SKIP
        tags = None
        if dictionary.get("tags") is not None:
            tags = [
                ResourceTagsV1.from_dictionary(x)
                    for x in dictionary.get("tags")
            ]
        else:
            tags = APIHelper.SKIP
        pg_config =\
            PostgresConfiguration.from_dictionary(
                dictionary.get("pgConfig"))\
                if "pgConfig" in dictionary.keys()\
                else APIHelper.SKIP
        pg_bouncer_config =\
            dictionary.get("pgBouncerConfig")\
            if dictionary.get("pgBouncerConfig")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   provider,
                   region,
                   size,
                   postgres_version,
                   ha_type,
                   tags,
                   pg_config,
                   pg_bouncer_config,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _provider=self.provider
        _region=self.region
        _postgres_version=(
            self.postgres_version
            if hasattr(self, "postgres_version")
            else None
        )
        _size=self.size
        _ha_type=(
            self.ha_type
            if hasattr(self, "ha_type")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _pg_config=(
            self.pg_config
            if hasattr(self, "pg_config")
            else None
        )
        _pg_bouncer_config=(
            self.pg_bouncer_config
            if hasattr(self, "pg_bouncer_config")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"provider={_provider!r}, "
            f"region={_region!r}, "
            f"postgres_version={_postgres_version!r}, "
            f"size={_size!r}, "
            f"ha_type={_ha_type!r}, "
            f"tags={_tags!r}, "
            f"pg_config={_pg_config!r}, "
            f"pg_bouncer_config={_pg_bouncer_config!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _provider=self.provider
        _region=self.region
        _postgres_version=(
            self.postgres_version
            if hasattr(self, "postgres_version")
            else None
        )
        _size=self.size
        _ha_type=(
            self.ha_type
            if hasattr(self, "ha_type")
            else None
        )
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _pg_config=(
            self.pg_config
            if hasattr(self, "pg_config")
            else None
        )
        _pg_bouncer_config=(
            self.pg_bouncer_config
            if hasattr(self, "pg_bouncer_config")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"provider={_provider!s}, "
            f"region={_region!s}, "
            f"postgres_version={_postgres_version!s}, "
            f"size={_size!s}, "
            f"ha_type={_ha_type!s}, "
            f"tags={_tags!s}, "
            f"pg_config={_pg_config!s}, "
            f"pg_bouncer_config={_pg_bouncer_config!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
