"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ReadPreference(object):
    """Implementation of the 'ReadPreference' enum.

    MongoDB read preference for replica set reads.

    Attributes:
        PRIMARY: The enum member of type str.
        PRIMARYPREFERRED: The enum member of type str.
        SECONDARY: The enum member of type str.
        SECONDARYPREFERRED: The enum member of type str.
        NEAREST: The enum member of type str.

    """

    PRIMARY = "primary"

    PRIMARYPREFERRED = "primaryPreferred"

    SECONDARY = "secondary"

    SECONDARYPREFERRED = "secondaryPreferred"

    NEAREST = "nearest"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
