"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.scim_group_member import (
    ScimGroupMember,
)


class ScimGroupPostRequest(object):
    """Implementation of the 'ScimGroupPostRequest' model.

    Attributes:
        schemas (List[str]): SCIM schema URIs. Must include
            "urn:ietf:params:scim:schemas:core:2.0:Group".
        external_id (str): Identifier for the resource as defined by the provisioning
            client.
        display_name (str): Human-readable name for the Group. Maps to Role name.
        members (List[ScimGroupMember]): Members of the Group.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "schemas": "schemas",
        "display_name": "displayName",
        "external_id": "externalId",
        "members": "members",
    }

    _optionals = [
        "external_id",
        "members",
    ]

    def __init__(
        self,
        schemas=None,
        display_name=None,
        external_id=APIHelper.SKIP,
        members=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ScimGroupPostRequest instance."""
        # Initialize members of the class
        self.schemas = schemas
        if external_id is not APIHelper.SKIP:
            self.external_id = external_id
        self.display_name = display_name
        if members is not APIHelper.SKIP:
            self.members = members

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        schemas =\
            dictionary.get("schemas")\
            if dictionary.get("schemas")\
                else None
        display_name =\
            dictionary.get("displayName")\
            if dictionary.get("displayName")\
                else None
        external_id =\
            dictionary.get("externalId")\
            if dictionary.get("externalId")\
                else APIHelper.SKIP
        members = None
        if dictionary.get("members") is not None:
            members = [
                ScimGroupMember.from_dictionary(x)
                    for x in dictionary.get("members")
            ]
        else:
            members = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(schemas,
                   display_name,
                   external_id,
                   members,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _schemas=self.schemas
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _display_name=self.display_name
        _members=(
            self.members
            if hasattr(self, "members")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"schemas={_schemas!r}, "
            f"external_id={_external_id!r}, "
            f"display_name={_display_name!r}, "
            f"members={_members!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _schemas=self.schemas
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _display_name=self.display_name
        _members=(
            self.members
            if hasattr(self, "members")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"schemas={_schemas!s}, "
            f"external_id={_external_id!s}, "
            f"display_name={_display_name!s}, "
            f"members={_members!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
