"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ScimUserAddress(object):
    """Implementation of the 'ScimUserAddress' model.

    Attributes:
        formatted (str): The full mailing address, formatted for display or use with
            a mailing label.
        street_address (str): The full street address component.
        locality (str): The city or locality component.
        region (str): The state or region component.
        postal_code (str): The zip code or postal code component.
        country (str): The country name component.
        mtype (str): Type of address (e.g., "work", "home", "other").
        primary (bool): A Boolean value indicating the preferred mailing address.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "formatted": "formatted",
        "street_address": "streetAddress",
        "locality": "locality",
        "region": "region",
        "postal_code": "postalCode",
        "country": "country",
        "mtype": "type",
        "primary": "primary",
    }

    _optionals = [
        "formatted",
        "street_address",
        "locality",
        "region",
        "postal_code",
        "country",
        "mtype",
        "primary",
    ]

    def __init__(
        self,
        formatted=APIHelper.SKIP,
        street_address=APIHelper.SKIP,
        locality=APIHelper.SKIP,
        region=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        country=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        primary=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ScimUserAddress instance."""
        # Initialize members of the class
        if formatted is not APIHelper.SKIP:
            self.formatted = formatted
        if street_address is not APIHelper.SKIP:
            self.street_address = street_address
        if locality is not APIHelper.SKIP:
            self.locality = locality
        if region is not APIHelper.SKIP:
            self.region = region
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if country is not APIHelper.SKIP:
            self.country = country
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if primary is not APIHelper.SKIP:
            self.primary = primary

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        formatted =\
            dictionary.get("formatted")\
            if dictionary.get("formatted")\
                else APIHelper.SKIP
        street_address =\
            dictionary.get("streetAddress")\
            if dictionary.get("streetAddress")\
                else APIHelper.SKIP
        locality =\
            dictionary.get("locality")\
            if dictionary.get("locality")\
                else APIHelper.SKIP
        region =\
            dictionary.get("region")\
            if dictionary.get("region")\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postalCode")\
            if dictionary.get("postalCode")\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        primary =\
            dictionary.get("primary")\
            if "primary" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(formatted,
                   street_address,
                   locality,
                   region,
                   postal_code,
                   country,
                   mtype,
                   primary,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _formatted=(
            self.formatted
            if hasattr(self, "formatted")
            else None
        )
        _street_address=(
            self.street_address
            if hasattr(self, "street_address")
            else None
        )
        _locality=(
            self.locality
            if hasattr(self, "locality")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _primary=(
            self.primary
            if hasattr(self, "primary")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"formatted={_formatted!r}, "
            f"street_address={_street_address!r}, "
            f"locality={_locality!r}, "
            f"region={_region!r}, "
            f"postal_code={_postal_code!r}, "
            f"country={_country!r}, "
            f"mtype={_mtype!r}, "
            f"primary={_primary!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _formatted=(
            self.formatted
            if hasattr(self, "formatted")
            else None
        )
        _street_address=(
            self.street_address
            if hasattr(self, "street_address")
            else None
        )
        _locality=(
            self.locality
            if hasattr(self, "locality")
            else None
        )
        _region=(
            self.region
            if hasattr(self, "region")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _primary=(
            self.primary
            if hasattr(self, "primary")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"formatted={_formatted!s}, "
            f"street_address={_street_address!s}, "
            f"locality={_locality!s}, "
            f"region={_region!s}, "
            f"postal_code={_postal_code!s}, "
            f"country={_country!s}, "
            f"mtype={_mtype!s}, "
            f"primary={_primary!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
