"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)
from openapispecforclickhousecloud.models.scim_user import (
    ScimUser,
)


class ScimListResponse(object):
    """Implementation of the 'ScimListResponse' model.

    Attributes:
        schemas (List[str]): Must be
            ["urn:ietf:params:scim:api:messages:2.0:ListResponse"].
        total_results (int): Total number of results matching the query.
        start_index (int): 1-based index of the first result in the current set.
        items_per_page (int): Number of resources returned in this response.
        resources (List[ScimUser]): Array of SCIM User resources.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "schemas": "schemas",
        "total_results": "totalResults",
        "start_index": "startIndex",
        "items_per_page": "itemsPerPage",
        "resources": "Resources",
    }

    def __init__(
        self,
        schemas=None,
        total_results=None,
        start_index=None,
        items_per_page=None,
        resources=None,
        additional_properties=None):
        """Initialize a ScimListResponse instance."""
        # Initialize members of the class
        self.schemas = schemas
        self.total_results = total_results
        self.start_index = start_index
        self.items_per_page = items_per_page
        self.resources = resources

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        schemas =\
            dictionary.get("schemas")\
            if dictionary.get("schemas")\
                else None
        total_results =\
            dictionary.get("totalResults")\
            if dictionary.get("totalResults")\
                else None
        start_index =\
            dictionary.get("startIndex")\
            if dictionary.get("startIndex")\
                else None
        items_per_page =\
            dictionary.get("itemsPerPage")\
            if dictionary.get("itemsPerPage")\
                else None
        resources = None
        if dictionary.get("Resources") is not None:
            resources = [
                ScimUser.from_dictionary(x)
                    for x in dictionary.get("Resources")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(schemas,
                   total_results,
                   start_index,
                   items_per_page,
                   resources,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _schemas=self.schemas
        _total_results=self.total_results
        _start_index=self.start_index
        _items_per_page=self.items_per_page
        _resources=self.resources
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"schemas={_schemas!r}, "
            f"total_results={_total_results!r}, "
            f"start_index={_start_index!r}, "
            f"items_per_page={_items_per_page!r}, "
            f"resources={_resources!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _schemas=self.schemas
        _total_results=self.total_results
        _start_index=self.start_index
        _items_per_page=self.items_per_page
        _resources=self.resources
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"schemas={_schemas!s}, "
            f"total_results={_total_results!s}, "
            f"start_index={_start_index!s}, "
            f"items_per_page={_items_per_page!s}, "
            f"resources={_resources!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
