"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ServiceScalingPatchRequest(object):
    """Implementation of the 'ServiceScalingPatchRequest' model.

    Attributes:
        min_total_memory_gb (float): DEPRECATED - inaccurate for services with
            non-default numbers of replicas. Use `minReplicaMemoryGb` instead.
            Minimum memory of three workers during auto-scaling in Gb. Available only
            for 'production' services. Must be a multiple of 12 and greater than or
            equal to 24. Always absent for horizontal-autoscaling services (replica
            count is variable).
        max_total_memory_gb (float): DEPRECATED - inaccurate for services with
            non-default numbers of replicas. Use `maxReplicaMemoryGb` instead.
            Maximum memory of three workers during auto-scaling in Gb. Available only
            for 'production' services. Must be a multiple of 12 and lower than or
            equal to 360 for non paid services or 1068 for paid services. Always
            absent for horizontal-autoscaling services (replica count is variable).
        num_replicas (int): Number of replicas for the service. The number of
            replicas must be between 2 and 50 for the first service in a warehouse.
            Services that are created in an existing warehouse can have a number of
            replicas as low as 1. Further restrictions may apply based on your
            organization's tier and its per-warehouse replica limit. It defaults to 1
            for the BASIC tier and 3 for the SCALE and ENTERPRISE tiers.
        idle_scaling (bool): When set to true the service is allowed to scale down to
            zero when idle. True by default.
        idle_timeout_minutes (float): Set minimum idling timeout (in minutes). Must
            be >= 5 minutes.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "min_total_memory_gb": "minTotalMemoryGb",
        "max_total_memory_gb": "maxTotalMemoryGb",
        "num_replicas": "numReplicas",
        "idle_scaling": "idleScaling",
        "idle_timeout_minutes": "idleTimeoutMinutes",
    }

    _optionals = [
        "min_total_memory_gb",
        "max_total_memory_gb",
        "num_replicas",
        "idle_scaling",
        "idle_timeout_minutes",
    ]

    def __init__(
        self,
        min_total_memory_gb=APIHelper.SKIP,
        max_total_memory_gb=APIHelper.SKIP,
        num_replicas=APIHelper.SKIP,
        idle_scaling=APIHelper.SKIP,
        idle_timeout_minutes=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ServiceScalingPatchRequest instance."""
        # Initialize members of the class
        if min_total_memory_gb is not APIHelper.SKIP:
            self.min_total_memory_gb = min_total_memory_gb
        if max_total_memory_gb is not APIHelper.SKIP:
            self.max_total_memory_gb = max_total_memory_gb
        if num_replicas is not APIHelper.SKIP:
            self.num_replicas = num_replicas
        if idle_scaling is not APIHelper.SKIP:
            self.idle_scaling = idle_scaling
        if idle_timeout_minutes is not APIHelper.SKIP:
            self.idle_timeout_minutes = idle_timeout_minutes

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        min_total_memory_gb =\
            dictionary.get("minTotalMemoryGb")\
            if dictionary.get("minTotalMemoryGb")\
                else APIHelper.SKIP
        max_total_memory_gb =\
            dictionary.get("maxTotalMemoryGb")\
            if dictionary.get("maxTotalMemoryGb")\
                else APIHelper.SKIP
        num_replicas =\
            dictionary.get("numReplicas")\
            if dictionary.get("numReplicas")\
                else APIHelper.SKIP
        idle_scaling =\
            dictionary.get("idleScaling")\
            if "idleScaling" in dictionary.keys()\
                else APIHelper.SKIP
        idle_timeout_minutes =\
            dictionary.get("idleTimeoutMinutes")\
            if dictionary.get("idleTimeoutMinutes")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(min_total_memory_gb,
                   max_total_memory_gb,
                   num_replicas,
                   idle_scaling,
                   idle_timeout_minutes,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _min_total_memory_gb=(
            self.min_total_memory_gb
            if hasattr(self, "min_total_memory_gb")
            else None
        )
        _max_total_memory_gb=(
            self.max_total_memory_gb
            if hasattr(self, "max_total_memory_gb")
            else None
        )
        _num_replicas=(
            self.num_replicas
            if hasattr(self, "num_replicas")
            else None
        )
        _idle_scaling=(
            self.idle_scaling
            if hasattr(self, "idle_scaling")
            else None
        )
        _idle_timeout_minutes=(
            self.idle_timeout_minutes
            if hasattr(self, "idle_timeout_minutes")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"min_total_memory_gb={_min_total_memory_gb!r}, "
            f"max_total_memory_gb={_max_total_memory_gb!r}, "
            f"num_replicas={_num_replicas!r}, "
            f"idle_scaling={_idle_scaling!r}, "
            f"idle_timeout_minutes={_idle_timeout_minutes!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _min_total_memory_gb=(
            self.min_total_memory_gb
            if hasattr(self, "min_total_memory_gb")
            else None
        )
        _max_total_memory_gb=(
            self.max_total_memory_gb
            if hasattr(self, "max_total_memory_gb")
            else None
        )
        _num_replicas=(
            self.num_replicas
            if hasattr(self, "num_replicas")
            else None
        )
        _idle_scaling=(
            self.idle_scaling
            if hasattr(self, "idle_scaling")
            else None
        )
        _idle_timeout_minutes=(
            self.idle_timeout_minutes
            if hasattr(self, "idle_timeout_minutes")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"min_total_memory_gb={_min_total_memory_gb!s}, "
            f"max_total_memory_gb={_max_total_memory_gb!s}, "
            f"num_replicas={_num_replicas!s}, "
            f"idle_scaling={_idle_scaling!s}, "
            f"idle_timeout_minutes={_idle_timeout_minutes!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
