"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ServiceEndpoint(object):
    """Implementation of the 'ServiceEndpoint' model.

    Attributes:
        protocol (Protocol): Endpoint protocol: 'https', 'nativesecure', 'mysql'.
        host (str): Service host name
        port (float): Numeric port
        username (str): Optional username for the endpoint
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "protocol": "protocol",
        "host": "host",
        "port": "port",
        "username": "username",
    }

    _optionals = [
        "protocol",
        "host",
        "port",
        "username",
    ]

    _nullables = [
        "username",
    ]

    def __init__(
        self,
        protocol=APIHelper.SKIP,
        host=APIHelper.SKIP,
        port=APIHelper.SKIP,
        username=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ServiceEndpoint instance."""
        # Initialize members of the class
        if protocol is not APIHelper.SKIP:
            self.protocol = protocol
        if host is not APIHelper.SKIP:
            self.host = host
        if port is not APIHelper.SKIP:
            self.port = port
        if username is not APIHelper.SKIP:
            self.username = username

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        protocol =\
            dictionary.get("protocol")\
            if dictionary.get("protocol")\
                else APIHelper.SKIP
        host =\
            dictionary.get("host")\
            if dictionary.get("host")\
                else APIHelper.SKIP
        port =\
            dictionary.get("port")\
            if dictionary.get("port")\
                else APIHelper.SKIP
        username =\
            dictionary.get("username")\
            if "username" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(protocol,
                   host,
                   port,
                   username,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _protocol=(
            self.protocol
            if hasattr(self, "protocol")
            else None
        )
        _host=(
            self.host
            if hasattr(self, "host")
            else None
        )
        _port=(
            self.port
            if hasattr(self, "port")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"protocol={_protocol!r}, "
            f"host={_host!r}, "
            f"port={_port!r}, "
            f"username={_username!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _protocol=(
            self.protocol
            if hasattr(self, "protocol")
            else None
        )
        _host=(
            self.host
            if hasattr(self, "host")
            else None
        )
        _port=(
            self.port
            if hasattr(self, "port")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"protocol={_protocol!s}, "
            f"host={_host!s}, "
            f"port={_port!s}, "
            f"username={_username!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
