"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ServiceEndpointChange(object):
    """Implementation of the 'ServiceEndpointChange' model.

    Attributes:
        protocol (Protocol1): Endpoint protocol
        enabled (bool): Enable or disable the endpoint
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "protocol": "protocol",
        "enabled": "enabled",
    }

    _optionals = [
        "protocol",
        "enabled",
    ]

    def __init__(
        self,
        protocol=APIHelper.SKIP,
        enabled=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ServiceEndpointChange instance."""
        # Initialize members of the class
        if protocol is not APIHelper.SKIP:
            self.protocol = protocol
        if enabled is not APIHelper.SKIP:
            self.enabled = enabled

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        protocol =\
            dictionary.get("protocol")\
            if dictionary.get("protocol")\
                else APIHelper.SKIP
        enabled =\
            dictionary.get("enabled")\
            if "enabled" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(protocol,
                   enabled,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _protocol=(
            self.protocol
            if hasattr(self, "protocol")
            else None
        )
        _enabled=(
            self.enabled
            if hasattr(self, "enabled")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"protocol={_protocol!r}, "
            f"enabled={_enabled!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _protocol=(
            self.protocol
            if hasattr(self, "protocol")
            else None
        )
        _enabled=(
            self.enabled
            if hasattr(self, "enabled")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"protocol={_protocol!s}, "
            f"enabled={_enabled!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
