"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class ServicePasswordPatchRequest(object):
    """Implementation of the 'ServicePasswordPatchRequest' model.

    Attributes:
        new_password_hash (str): Optional password hash. Used to avoid password
            transmission over network. If not provided a new password is generated
            and is provided in the response. Otherwise this hash is used. Algorithm:
            echo -n "yourpassword" | sha256sum | tr -d '-' | xxd -r -p | base64
        new_double_sha_1_hash (str): Optional double SHA1 password hash for MySQL
            protocol. If newPasswordHash is not provided this key will be ignored and
            the generated password will be used. Algorithm: echo -n "yourpassword" |
            sha1sum | tr -d '-' | xxd -r -p | sha1sum | tr -d '-'
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "new_password_hash": "newPasswordHash",
        "new_double_sha_1_hash": "newDoubleSha1Hash",
    }

    _optionals = [
        "new_password_hash",
        "new_double_sha_1_hash",
    ]

    def __init__(
        self,
        new_password_hash=APIHelper.SKIP,
        new_double_sha_1_hash=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ServicePasswordPatchRequest instance."""
        # Initialize members of the class
        if new_password_hash is not APIHelper.SKIP:
            self.new_password_hash = new_password_hash
        if new_double_sha_1_hash is not APIHelper.SKIP:
            self.new_double_sha_1_hash = new_double_sha_1_hash

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        new_password_hash =\
            dictionary.get("newPasswordHash")\
            if dictionary.get("newPasswordHash")\
                else APIHelper.SKIP
        new_double_sha_1_hash =\
            dictionary.get("newDoubleSha1Hash")\
            if dictionary.get("newDoubleSha1Hash")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(new_password_hash,
                   new_double_sha_1_hash,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _new_password_hash=(
            self.new_password_hash
            if hasattr(self, "new_password_hash")
            else None
        )
        _new_double_sha_1_hash=(
            self.new_double_sha_1_hash
            if hasattr(self, "new_double_sha_1_hash")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"new_password_hash={_new_password_hash!r}, "
            f"new_double_sha_1_hash={_new_double_sha_1_hash!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _new_password_hash=(
            self.new_password_hash
            if hasattr(self, "new_password_hash")
            else None
        )
        _new_double_sha_1_hash=(
            self.new_double_sha_1_hash
            if hasattr(self, "new_double_sha_1_hash")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"new_password_hash={_new_password_hash!s}, "
            f"new_double_sha_1_hash={_new_double_sha_1_hash!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
