"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class SourceMetricType(object):
    """Implementation of the 'SourceMetricType' enum.

    Metric type when source is metrics

    Attributes:
        SUM: The enum member of type str.
        GAUGE: The enum member of type str.
        HISTOGRAM: The enum member of type str.
        SUMMARY: The enum member of type str.
        ENUM_EXPONENTIAL_HISTOGRAM: The enum member of type str.

    """

    _all_values = ["sum", "gauge", "histogram", "summary", "exponential histogram"]
    SUM = "sum"

    GAUGE = "gauge"

    HISTOGRAM = "histogram"

    SUMMARY = "summary"

    ENUM_EXPONENTIAL_HISTOGRAM = "exponential histogram"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
