"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Type5(object):
    """Implementation of the 'Type5' enum.

    Type of the ObjectStorage source.

    Attributes:
        S3: The enum member of type str.
        GCS: The enum member of type str.
        DOSPACES: The enum member of type str.
        AZUREBLOBSTORAGE: The enum member of type str.
        CLOUDFLARER2: The enum member of type str.
        OVHOBJECTSTORAGE: The enum member of type str.

    """

    S3 = "s3"

    GCS = "gcs"

    DOSPACES = "dospaces"

    AZUREBLOBSTORAGE = "azureblobstorage"

    CLOUDFLARER2 = "cloudflarer2"

    OVHOBJECTSTORAGE = "ovhobjectstorage"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
