"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class UdfUploadSession(object):
    """Implementation of the 'UdfUploadSession' model.

    Attributes:
        upload_id (uuid|str): Identifier of the uploaded source archive.
        upload_url (str): Presigned URL for uploading the source archive.
        expires_at (datetime): Presigned-URL expiry timestamp.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "upload_id": "uploadId",
        "upload_url": "uploadUrl",
        "expires_at": "expiresAt",
    }

    def __init__(
        self,
        upload_id=None,
        upload_url=None,
        expires_at=None):
        """Initialize a UdfUploadSession instance."""
        # Initialize members of the class
        self.upload_id = upload_id
        self.upload_url = upload_url
        self.expires_at =\
             APIHelper.apply_datetime_converter(
            expires_at, APIHelper.RFC3339DateTime)\
             if expires_at else None

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        upload_id =\
            dictionary.get("uploadId")\
            if dictionary.get("uploadId")\
                else None
        upload_url =\
            dictionary.get("uploadUrl")\
            if dictionary.get("uploadUrl")\
                else None
        expires_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expiresAt")).datetime\
            if dictionary.get("expiresAt") else None

        # Return an object of this model
        return cls(upload_id,
                   upload_url,
                   expires_at)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _upload_id=self.upload_id
        _upload_url=self.upload_url
        _expires_at=self.expires_at
        return (
            f"{self.__class__.__name__}("
            f"upload_id={_upload_id!r}, "
            f"upload_url={_upload_url!r}, "
            f"expires_at={_expires_at!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _upload_id=self.upload_id
        _upload_url=self.upload_url
        _expires_at=self.expires_at
        return (
            f"{self.__class__.__name__}("
            f"upload_id={_upload_id!s}, "
            f"upload_url={_upload_url!s}, "
            f"expires_at={_expires_at!s}, "
            f")"
        )
