"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class UpgradeWindow(object):
    """Implementation of the 'UpgradeWindow' model.

    Attributes:
        weekday (int): Day of the week the upgrade window starts. 0 = Sunday, 1 =
            Monday, …, 6 = Saturday.
        start_hour_utc (StartHourUtc): UTC hour when the upgrade window starts. Must
            be one of 0, 6, 12, or 18.
        duration (int): Length of the upgrade window in hours. Currently only a
            6-hour window is supported.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "weekday": "weekday",
        "start_hour_utc": "startHourUtc",
        "duration": "duration",
    }

    def __init__(
        self,
        weekday=None,
        start_hour_utc=None,
        additional_properties=None):
        """Initialize a UpgradeWindow instance."""
        # Initialize members of the class
        self.weekday = weekday
        self.start_hour_utc = start_hour_utc
        self.duration = 6

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        weekday =\
            dictionary.get("weekday")\
            if dictionary.get("weekday")\
                else None
        start_hour_utc =\
            dictionary.get("startHourUtc")\
            if dictionary.get("startHourUtc")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(weekday,
                   start_hour_utc,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _weekday=self.weekday
        _start_hour_utc=self.start_hour_utc
        _duration=self.duration
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"weekday={_weekday!r}, "
            f"start_hour_utc={_start_hour_utc!r}, "
            f"duration={_duration!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _weekday=self.weekday
        _start_hour_utc=self.start_hour_utc
        _duration=self.duration
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"weekday={_weekday!s}, "
            f"start_hour_utc={_start_hour_utc!s}, "
            f"duration={_duration!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
