"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from openapispecforclickhousecloud.api_helper import (
    APIHelper,
)


class UsageCostMetrics(object):
    """Implementation of the 'UsageCostMetrics' model.

    Attributes:
        storage_chc (float): Cost of storage in ClickHouse Credits (CHCs). Applies to
            dataWarehouse entities.
        backup_chc (float): Cost of backup in ClickHouse Credits (CHCs). Applies to
            dataWarehouse entities.
        compute_chc (float): Cost of compute in ClickHouse Credits (CHCs). Applies to
            service and clickpipe entities.
        data_transfer_chc (float): Cost of data transfer in ClickHouse Credits
            (CHCs). Applies to clickpipe entities.
        initial_load_chc (float): Cost of initial load and resyncs in ClickHouse
            Credits (CHCs). Applies to clickpipe entities.
        public_data_transfer_chc (float): Cost of data transfer in ClickHouse Credits
            (CHCs). Applies to service entities.
        inter_region_tier_1_data_transfer_chc (float): Cost of tier1 inter-region
            data transfer in ClickHouse Credits (CHCs). Applies to service entities.
        inter_region_tier_2_data_transfer_chc (float): Cost of tier2 inter-region
            data transfer in ClickHouse Credits (CHCs). Applies to service entities.
        inter_region_tier_3_data_transfer_chc (float): Cost of tier3 inter-region
            data transfer in ClickHouse Credits (CHCs). Applies to service entities.
        inter_region_tier_4_data_transfer_chc (float): Cost of tier4 inter-region
            data transfer in ClickHouse Credits (CHCs). Applies to service entities.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "storage_chc": "storageCHC",
        "backup_chc": "backupCHC",
        "compute_chc": "computeCHC",
        "data_transfer_chc": "dataTransferCHC",
        "initial_load_chc": "initialLoadCHC",
        "public_data_transfer_chc": "publicDataTransferCHC",
        "inter_region_tier_1_data_transfer_chc": "interRegionTier1DataTransferCHC",
        "inter_region_tier_2_data_transfer_chc": "interRegionTier2DataTransferCHC",
        "inter_region_tier_3_data_transfer_chc": "interRegionTier3DataTransferCHC",
        "inter_region_tier_4_data_transfer_chc": "interRegionTier4DataTransferCHC",
    }

    _optionals = [
        "storage_chc",
        "backup_chc",
        "compute_chc",
        "data_transfer_chc",
        "initial_load_chc",
        "public_data_transfer_chc",
        "inter_region_tier_1_data_transfer_chc",
        "inter_region_tier_2_data_transfer_chc",
        "inter_region_tier_3_data_transfer_chc",
        "inter_region_tier_4_data_transfer_chc",
    ]

    def __init__(
        self,
        storage_chc=APIHelper.SKIP,
        backup_chc=APIHelper.SKIP,
        compute_chc=APIHelper.SKIP,
        data_transfer_chc=APIHelper.SKIP,
        initial_load_chc=APIHelper.SKIP,
        public_data_transfer_chc=APIHelper.SKIP,
        inter_region_tier_1_data_transfer_chc=APIHelper.SKIP,
        inter_region_tier_2_data_transfer_chc=APIHelper.SKIP,
        inter_region_tier_3_data_transfer_chc=APIHelper.SKIP,
        inter_region_tier_4_data_transfer_chc=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UsageCostMetrics instance."""
        # Initialize members of the class
        if storage_chc is not APIHelper.SKIP:
            self.storage_chc = storage_chc
        if backup_chc is not APIHelper.SKIP:
            self.backup_chc = backup_chc
        if compute_chc is not APIHelper.SKIP:
            self.compute_chc = compute_chc
        if data_transfer_chc is not APIHelper.SKIP:
            self.data_transfer_chc = data_transfer_chc
        if initial_load_chc is not APIHelper.SKIP:
            self.initial_load_chc = initial_load_chc
        if public_data_transfer_chc is not APIHelper.SKIP:
            self.public_data_transfer_chc = public_data_transfer_chc
        if inter_region_tier_1_data_transfer_chc is not APIHelper.SKIP:
            self.inter_region_tier_1_data_transfer_chc =\
                 inter_region_tier_1_data_transfer_chc
        if inter_region_tier_2_data_transfer_chc is not APIHelper.SKIP:
            self.inter_region_tier_2_data_transfer_chc =\
                 inter_region_tier_2_data_transfer_chc
        if inter_region_tier_3_data_transfer_chc is not APIHelper.SKIP:
            self.inter_region_tier_3_data_transfer_chc =\
                 inter_region_tier_3_data_transfer_chc
        if inter_region_tier_4_data_transfer_chc is not APIHelper.SKIP:
            self.inter_region_tier_4_data_transfer_chc =\
                 inter_region_tier_4_data_transfer_chc

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        storage_chc =\
            dictionary.get("storageCHC")\
            if dictionary.get("storageCHC")\
                else APIHelper.SKIP
        backup_chc =\
            dictionary.get("backupCHC")\
            if dictionary.get("backupCHC")\
                else APIHelper.SKIP
        compute_chc =\
            dictionary.get("computeCHC")\
            if dictionary.get("computeCHC")\
                else APIHelper.SKIP
        data_transfer_chc =\
            dictionary.get("dataTransferCHC")\
            if dictionary.get("dataTransferCHC")\
                else APIHelper.SKIP
        initial_load_chc =\
            dictionary.get("initialLoadCHC")\
            if dictionary.get("initialLoadCHC")\
                else APIHelper.SKIP
        public_data_transfer_chc =\
            dictionary.get("publicDataTransferCHC")\
            if dictionary.get("publicDataTransferCHC")\
                else APIHelper.SKIP
        inter_region_tier_1_data_transfer_chc =\
            dictionary.get("interRegionTier1DataTransferCHC")\
            if dictionary.get("interRegionTier1DataTransferCHC")\
                else APIHelper.SKIP
        inter_region_tier_2_data_transfer_chc =\
            dictionary.get("interRegionTier2DataTransferCHC")\
            if dictionary.get("interRegionTier2DataTransferCHC")\
                else APIHelper.SKIP
        inter_region_tier_3_data_transfer_chc =\
            dictionary.get("interRegionTier3DataTransferCHC")\
            if dictionary.get("interRegionTier3DataTransferCHC")\
                else APIHelper.SKIP
        inter_region_tier_4_data_transfer_chc =\
            dictionary.get("interRegionTier4DataTransferCHC")\
            if dictionary.get("interRegionTier4DataTransferCHC")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(storage_chc,
                   backup_chc,
                   compute_chc,
                   data_transfer_chc,
                   initial_load_chc,
                   public_data_transfer_chc,
                   inter_region_tier_1_data_transfer_chc,
                   inter_region_tier_2_data_transfer_chc,
                   inter_region_tier_3_data_transfer_chc,
                   inter_region_tier_4_data_transfer_chc,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _storage_chc=(
            self.storage_chc
            if hasattr(self, "storage_chc")
            else None
        )
        _backup_chc=(
            self.backup_chc
            if hasattr(self, "backup_chc")
            else None
        )
        _compute_chc=(
            self.compute_chc
            if hasattr(self, "compute_chc")
            else None
        )
        _data_transfer_chc=(
            self.data_transfer_chc
            if hasattr(self, "data_transfer_chc")
            else None
        )
        _initial_load_chc=(
            self.initial_load_chc
            if hasattr(self, "initial_load_chc")
            else None
        )
        _public_data_transfer_chc=(
            self.public_data_transfer_chc
            if hasattr(self, "public_data_transfer_chc")
            else None
        )
        _inter_region_tier_1_data_transfer_chc=(
            self.inter_region_tier_1_data_transfer_chc
            if hasattr(self, "inter_region_tier_1_data_transfer_chc")
            else None
        )
        _inter_region_tier_2_data_transfer_chc=(
            self.inter_region_tier_2_data_transfer_chc
            if hasattr(self, "inter_region_tier_2_data_transfer_chc")
            else None
        )
        _inter_region_tier_3_data_transfer_chc=(
            self.inter_region_tier_3_data_transfer_chc
            if hasattr(self, "inter_region_tier_3_data_transfer_chc")
            else None
        )
        _inter_region_tier_4_data_transfer_chc=(
            self.inter_region_tier_4_data_transfer_chc
            if hasattr(self, "inter_region_tier_4_data_transfer_chc")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"storage_chc={_storage_chc!r}, "
            f"backup_chc={_backup_chc!r}, "
            f"compute_chc={_compute_chc!r}, "
            f"data_transfer_chc={_data_transfer_chc!r}, "
            f"initial_load_chc={_initial_load_chc!r}, "
            f"public_data_transfer_chc={_public_data_transfer_chc!r}, "
            f"inter_region_tier_1_data_transfer_chc={_inter_region_tier_1_data_transfer_chc!r}, "
            f"inter_region_tier_2_data_transfer_chc={_inter_region_tier_2_data_transfer_chc!r}, "
            f"inter_region_tier_3_data_transfer_chc={_inter_region_tier_3_data_transfer_chc!r}, "
            f"inter_region_tier_4_data_transfer_chc={_inter_region_tier_4_data_transfer_chc!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _storage_chc=(
            self.storage_chc
            if hasattr(self, "storage_chc")
            else None
        )
        _backup_chc=(
            self.backup_chc
            if hasattr(self, "backup_chc")
            else None
        )
        _compute_chc=(
            self.compute_chc
            if hasattr(self, "compute_chc")
            else None
        )
        _data_transfer_chc=(
            self.data_transfer_chc
            if hasattr(self, "data_transfer_chc")
            else None
        )
        _initial_load_chc=(
            self.initial_load_chc
            if hasattr(self, "initial_load_chc")
            else None
        )
        _public_data_transfer_chc=(
            self.public_data_transfer_chc
            if hasattr(self, "public_data_transfer_chc")
            else None
        )
        _inter_region_tier_1_data_transfer_chc=(
            self.inter_region_tier_1_data_transfer_chc
            if hasattr(self, "inter_region_tier_1_data_transfer_chc")
            else None
        )
        _inter_region_tier_2_data_transfer_chc=(
            self.inter_region_tier_2_data_transfer_chc
            if hasattr(self, "inter_region_tier_2_data_transfer_chc")
            else None
        )
        _inter_region_tier_3_data_transfer_chc=(
            self.inter_region_tier_3_data_transfer_chc
            if hasattr(self, "inter_region_tier_3_data_transfer_chc")
            else None
        )
        _inter_region_tier_4_data_transfer_chc=(
            self.inter_region_tier_4_data_transfer_chc
            if hasattr(self, "inter_region_tier_4_data_transfer_chc")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"storage_chc={_storage_chc!s}, "
            f"backup_chc={_backup_chc!s}, "
            f"compute_chc={_compute_chc!s}, "
            f"data_transfer_chc={_data_transfer_chc!s}, "
            f"initial_load_chc={_initial_load_chc!s}, "
            f"public_data_transfer_chc={_public_data_transfer_chc!s}, "
            f"inter_region_tier_1_data_transfer_chc={_inter_region_tier_1_data_transfer_chc!s}, "
            f"inter_region_tier_2_data_transfer_chc={_inter_region_tier_2_data_transfer_chc!s}, "
            f"inter_region_tier_3_data_transfer_chc={_inter_region_tier_3_data_transfer_chc!s}, "
            f"inter_region_tier_4_data_transfer_chc={_inter_region_tier_4_data_transfer_chc!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
