"""openapispecforclickhousecloud.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class V1OrganizationsUdfsResponse2(object):
    """Implementation of the 'V1 Organizations Udfs Response2' model.

    Attributes:
        status (int): HTTP status code.
        request_id (uuid|str): Unique id assigned to every request. UUIDv4

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "request_id": "requestId",
    }

    def __init__(
        self,
        status=None,
        request_id=None):
        """Initialize a V1OrganizationsUdfsResponse2 instance."""
        # Initialize members of the class
        self.status = status
        self.request_id = request_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        request_id =\
            dictionary.get("requestId")\
            if dictionary.get("requestId")\
                else None

        # Return an object of this model
        return cls(status,
                   request_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=self.status
        _request_id=self.request_id
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"request_id={_request_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        _request_id=self.request_id
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"request_id={_request_id!s}, "
            f")"
        )
